co-niverse/algorithm-study

yoonjin/0424/10818.py, yoonjin/0424/2438.py, yoonjin/0424/2439.py, yoonjin/0424/2440.py, yoonjin/0424/2441.py, yoonjin/0424/2442.py, yoonjin/0424/8393.py, yoonjin/0425/11726.py, yoonjin/0425/11727.py, yoonjin/0425/1463.py, yoonjin/0425/입출력.py
8393, 10818, 2438, 2439, 2440, 2441, 2442
=> [BOJ] 23-04-24 (입출력)

gibeom/23-04-25.py
https://www.acmicpc.net/problem/1753
다익스트라 알고리즘을 사용했다
처음에 `graph`의 2차원 리스트를 딕셔너리로 사용했었는데 중복된 간선이 있는지 계속 10%에서 틀렸다 2차원 리스트로 수정하니 해결,,
- 단일 시작점으로부터 다른 노드들까지 최단 경로를 구하는 알고리즘
- 양의 가중치일 경우만 사용 가능 (음의 가중치일 경우 사이클 발생)
- 시간복잡도: `O(ElogV)`
- 모든 간선 검사: `O(E)`
- 각 간선마다 힙에 삽입, 삭제 연산: `O(logE)`
- 대부분의 그래프는 V^2 > E (모든 노드가 연결되어 있을 경우 E의 개수는 V * (V - 1))
- 따라서 `O(logE)` = `O(logV)`
=> [BOJ] 1753 : 최단경로

yoonjin/0426/10844.py, yoonjin/0426/11057.py, yoonjin/0426/9095.py
📍 문제번호
---
[9095](https://www.acmicpc.net/problem/9095) 
[10844](https://www.acmicpc.net/problem/10844) 
[11057](https://www.acmicpc.net/problem/11057)
💡 느낀 점
---
규칙 찾다가 머리 터지는 줄 알았다 ..
원래 DP 문제는 규칙 찾는게 제일 관건인걸까 ??
=> [BOJ] 23-04-26 (DP)

yoonjin/0428/10799.py, yoonjin/0428/9012.py
스택 문제풀이
---
- [9012](https://www.acmicpc.net/problem/9012)
- [10799](https://www.acmicpc.net/problem/10799)
10799 쇠막대기
---
문제 이해하는게 너무 어려웠다 ..
레이저를 기준으로 숫자로 환산해서 풀 생각만 했었는데 그림을 먼저 보고 전체적인 구조를 이해하는게 중요한 것 같다.
**앞으로는 냅다 문제 풀지 말고 문제부터 이해해야지 !**
=> [BOJ] 23-04-28 스택

gibeom/23-04-28.py
https://www.acmicpc.net/problem/15686
- 2중 for문에서 집과 치킨집의 index를 구한다.
- `combinations()` 메서드로 치킨집에서 m개의 조합을 구한다.
- 한 조합마다 치킨 거리를 구하고 최소 치킨 거리를 계산한다.
=> [BOJ] 15686 : 치킨 배달 (23.04.28)

gibeom/23-04-29.py
https://www.acmicpc.net/problem/6603
- k개 중 6개의 조합을 출력한다
=> [BOJ] 6603 : 로또 (23.04.29)

gibeom/23-05-01.py
https://www.acmicpc.net/problem/2110
이 문제의 포인트는 집의 좌표를 이진 탐색하는 것이 아닌 공유기를 설치할 거리를 이진 탐색하는 것이다.
- `start`: 공유기를 설치할 수 있는 최소 거리이므로 1
- `end`: 공유기를 설치할 수 있는 최대 거리, c에 따라 최대 거리가 달라지므로 범위를 좁혀준다.
> 이진 탐색은 start와 end의 범위를 최대한 좁게 잡아야 시간을 많이 줄일 수 있다.
<br>
`binary_search()`
- `mid`: 공유기를 설치할 거리
- for문으로 집의 좌표를 순회하면서 공유기를 설치할 수 있는지 확인한다.
- 공유기 설치 개수에 따라 start와 end의 범위를 설정한다.
=> [BOJ] 2110 : 공유기 설치 (23.05.01)

yoonjin/0430/10610.py, yoonjin/0430/11047.py, yoonjin/0502/10845.py, yoonjin/0502/10866.py, yoonjin/0502/9996.py
230430 그리디
---
[11047](https://www.acmicpc.net/problem/11047)
[10610](https://www.acmicpc.net/problem/11047)
**join 함수**
문자열(list) 합칠 때 사용
'구분자'.join(리스트)
-> print(''.join(n))
230502
---
[10845 queue](https://www.acmicpc.net/problem/10845)
[10866 deque](https://www.acmicpc.net/problem/10866)
[9996 문자열](https://www.acmicpc.net/problem/9996)
=> [BOJ] 23-04-30, 23-05-02

gibeom/23-04-28.py, gibeom/23-04-29.py, gibeom/23-05-01.py, gibeom/23-05-02.py
https://www.acmicpc.net/problem/2630
커밋 해쉬번호가 안맞아서 이전꺼도 올라왔는데 **2630 : 색종이 만들기**만 보면 돼용
``` python
def cut(x_start, x_end, y_start, y_end):
global white, blue
tot = (x_end - x_start) ** 2
color = papers[y_start][x_start]
cnt = 0
for i in range(y_start, y_end):
for j in range(x_start, x_end):
if papers[i][j] == color:
cnt += 1
if cnt == tot:
if color == 1:
blue += 1
else:
white += 1
else:
cut(x_start, (x_start + x_end)//2, y_start, (y_start + y_end)//2)
cut((x_start + x_end)//2, x_end, y_start, (y_start + y_end)//2)
cut(x_start, (x_start + x_end)//2, (y_start + y_end)//2, y_end)
cut((x_start + x_end)//2, x_end, (y_start + y_end)//2, y_end)
papers = [list(map(int, stdin.readline().split())) for _ in range(n)]
white = 0
blue = 0
cut(0, n, 0, n) …
```
=> [BOJ] 2630 : 색종이 만들기 (23.05.02)

gaeun/2023:05:03:BOJ1874.py
=> 2023/05/03 BOJ 1874 :  스택 수열

yoonjin/0503/1260.py
[1260 - DFS, BFS 개념 문제](https://www.acmicpc.net/problem/1260)
---
DFS, BFS를 구현하는 다양한 방법이 있는 것 같은데 다 익히기가 힘드네요 !
이번주 목표는 DFS BFS 정복입니다 !! 화이팅 !
=> [BOJ] DFS,BFS 기초

yoonjin/0505/11650.py, yoonjin/0505/9465.py
[9465 DP](https://www.acmicpc.net/problem/9465)
- 푸는 방법까지 생각해내는 데에도 시간이 많이 걸렸고, 실제 코드로 옮기는 것도 어려웠다.
[11650 좌표 정렬](https://www.acmicpc.net/problem/11650)
- 단순 좌표 정렬 문제인데, [x,y]로 묶어서 그냥 input()으로 받고, int형으로 받지 않아서 틀렸었다.
=> [BOJ] 23-05-05 (9465, 11650)

yoonjin/0506/11656.py, yoonjin/0506/13458.py
[13458](https://www.acmicpc.net/problem/13458)
-
자신감 상승을 위해 삼성 역량 테스트 기출 중에 제일 쉬운 문제를 풀었는데
시간 초과로 틀려서 당황했다 ㅎㅎ
> 이중 중첩문 있으면 시간 초과 뜰거 생각하고 최대한 중첩 안되게 풀이
> 뺄셈 여러번 하는건 나눗셈으로 풀자 !
[11656](https://www.acmicpc.net/problem/11656)
=> [BOJ] 23-05-06 (11656, 13458)

gaeun/2023:05:05:BOJ2512.py
문제를 이해하는 능력이 부족한 것 같음
이분 탐색의 중요한 포인트는 start와 end를 바꾸는 기준인 것 같다. 난 이 기준을 정하는게 어려운 듯..!
이분 탐색을 이용해서 상한값이 총 금액을 넘지 않으면서도, 그 중에서 최대값을 구하는 방식으로 풀었음
=> 2023/05/05 BOJ 2512 : 예산

yoonjin/0508/1158.py, yoonjin/0508/11728.py
[11728](https://www.acmicpc.net/problem/11728)
--
- 정렬은 그냥 sort 함수 사용해서 쉽게 가능했다. 
- 출력할 때 join 함수를 사용하는게 아직 익숙하지 않은데, 자주 사용하도록 해야겠다.
[1158](https://www.acmicpc.net/problem/1158)
--
- 처음에는 그냥 list로 풀었는데 시간초과 떠서 deque으로 바꿔서 풀이했다.
- 출력할 때 replace 함수로 특정 부분을 바꿀 수 있는데, **list를 str()로 받은 이후에 가능하다.**
=> [BOJ] 23-05-08 (11728, 1158)

gaeun/2023:05:08:BOJ1932.py
알고리즘 중에서 DP가 가장 약한데, 첫 제출에 맞춰서 기분이 좋았음
점화식을 사용해야한다는 의무감때문에  트리 한 라인 당 최댓값을 구해야할지 많은 고민을 했었다,
그런데 일일히 최댓값을 노가다로 구해보니, 중복되는 부분을 찾을 수 있었고, 그 부분을 점화식으로 만들려고 노력했다 !
점화식 세우는게 가장 어려웠는데,,! 오늘은 생각보다 쉽게 풀었음 히히 나 조금 성장했..나..?ㅋ
=> 2023/05/08 BOJ 1932 : 정수 삼각형

gibeom/23-05-08.py
https://www.acmicpc.net/problem/10799
- 레이저를 의미하는 `()`를 `|`로 치환한 후 순회한다.
- `(`면 새로운 쇠 막대기이므로 stack을 1 증가시킨다.
- `)`면 쇠 막대기의 끝이므로 stack을 1 감소시킨다.
- `|`면 stack에 있는 쇠 막대기 개수만큼 잘려나가므로 `bar_cnt`를 stack 만큼 증가시킨다.
=> [BOJ] 10799 : 쇠막대기 (23.05.08)

yoonjin/0509/11399.py
[11399](https://www.acmicpc.net/problem/11399)
- 문제 풀이는 배열 순서를 정렬한 이후 다 더하는 경우가 최소값임을 판단하면 쉬웠다.
- 첫번째 풀이 : for문을 중첩 사용하여 풀었는데 시간 초과가 날 줄 알았는데 안나서 맞았다.
- 두번째 풀이 : for문 중첩을 없애고 싶어서 sum함수를 사용해서 **sum(times[:i+1])** 이렇게 풀었다.
=> [BOJ] 23-05-09 (11399)

gibeom/23-05-10.py
https://www.acmicpc.net/problem/14503
``` python
def change_cardinal_points():
global robot
if robot[2] == 0:
robot[2] = 3
else:
robot[2] -= 1
def move(r, c):
global robot
robot[0] = r
robot[1] = c
def find_unclean_area(r, c):
for d in direction:
nr, nc = r + d[0], c + d[1]
if room[nr][nc] == 0:
return True
return False
robot = [0, 0, 0]
robot[0], robot[1], robot[2] = map(int, stdin.readline().split())
room = [list(map(int, stdin.readline().split())) for _ in range(n)]
direction = [(-1, 0), (0, 1), (1, 0), (0, -1)]
cleaning_cnt = 0
running = True
while running:
r, c = robot[0], robot[1]
if room[r][c] == 0: # 현재 위치가 청소되지 않았을 경우
room[r][c] = 2 # 청소 상태로 변경
cleaning_cnt += 1 # 청소 횟수 증가
if find_unclean_area(r, c): # 청소가 안된 곳이 있을 …
```
=> [BOJ] 14503 : 로봇 청소기 (23.05.10)

gibeom/23-05-11.py
https://www.acmicpc.net/problem/3190
``` python
return r < 0 or r >= n or c < 0 or c >= n
def turn_direction(moving, i):
if moving == 'L':
return (i + 3) % 4
else:
return (i + 1) % 4
n, k = int(stdin.readline()), int(stdin.readline())
board = [[0] * n for _ in range(n)]
for _ in range(k):
r, c = map(int, stdin.readline().split())
board[r - 1][c - 1] = 1 # 사과 표시
L = int(stdin.readline())
moves = deque(stdin.readline().split() for _ in range(L)) # 방향 변환 정보
r = c = 0
snake = deque([(r, c)])
direction = [(-1, 0), (0, 1), (1, 0), (0, -1)]
d = 1 # direction의 인덱스
second = 0
while True:
second += 1
r, c = r + direction[d][0], c + direction[d][1] # 다음 머리 위치
if is_out_of_range(r, c) or (r, c) in snake: # 범위를 벗어났거나 몸에 …
```
=> [BOJ] 3190 : 뱀 (23.05.11)

gaeun/2023:05:10:BOJ2193.py
DP 문제인데, 피보나치와 비슷했음
다른 풀이와 유사 함
=> 2023/05/10 BOJ 2193 : 이친수 [DP]

yoonjin/0512/1065.py
[1065](https://www.acmicpc.net/problem/1065) 
처음에 list(map(int, i)) 이렇게 했다가 숫자는 각자리수로 자를 수가 없어서 런타임 에러가 발생했다.
이후 list(map(int,str(i))) 이렇게 수정 완료
=> [BOJ] 23-05-12 (1065)

gibeom/23-05-26.py
https://www.acmicpc.net/problem/14502
``` python
from itertools import combinations
def spread(new_wall):
tmp_lab = [i[:] for i in lab] # deep copy
for r, c in new_wall:
tmp_lab[r][c] = 1 # 새로운 벽 3개 세우기
q = deque(virus)
infection = 0 # 바이러스가 퍼져나간 개수
while q: # 바이러스 bfs
infection += 1
if 0 <= nr < n and 0 <= nc < m and tmp_lab[nr][nc] == 0: # 범위 내이고 0이면
tmp_lab[nr][nc] = 2 # 바이러스 전염
q.append((nr, nc))
return not_wall - infection # 남은 빈 칸의 개수
lab = [list(map(int, stdin.readline().split())) for _ in range(n)]
empty_space = []
virus = []
for j in range(m):
if lab[i][j] == 0:
empty_space.append((i, …
```
=> [BOJ] 14502 : 연구소 (23.05.26)

yoonjin/0529/1920.py, yoonjin/0529/2512.py
1. 기본 코드 암기
2. [1920번 풀이](https://www.acmicpc.net/problem/1920)
코드 잘 짠 것 같은데 계속 틀림. 알고 보니까 sort를 안함. 
3. [2512번 풀이](https://www.acmicpc.net/problem/2512)
이진 탐색 문제라고 해서 풀었는데 어떻게 써야 하는지 감이 안와서 다른 사람들 코드 참고함. 
아직도 감은 잘 안오지만.. 문제를 많이 풀다 보면 익숙해지겠지 ?!
**이진 탐색 할 때는 sort하고 시작하기**
=> [23-05-29] BOJ 1920, 2512

yoonjin/0530/1476.py
완전 탐색도 중요하다고 해서 풀어봤는데 그냥 규칙이랑 식 잘 찾으면 되는 것 같다 !
처음에는 (answer + 15) % e == 0 이런 식으로 조건문 작성했는데 (answer - e) % 15 == 0 이렇게 풀어야 하는 것이었다.
=> [23-05-30] 1476

gibeom/23-05-30.py
https://www.acmicpc.net/problem/15684
골드 3인데 정말 까다로웠던 문제,,
``` python
def is_same_vertical():
for j in range(1, n + 1):
start = j
for i in range(1, h + 1):
if ladder[i][j]:
j = ladder[i][j]
if start != j:
return False
return True
def dfs(cnt, depth, now):
global res
if is_same_vertical(): # 모든 세로선이 사다리를 탄 후 원래 세로선으로 되돌아오면 최솟값 갱신
res = min(res, cnt)
return
elif cnt == 3 or cnt >= res: # cnt가 3인데 위의 if문에 걸리지 않으면 가로선을 더 추가해야 한다는 얘기이므로 백트래킹
return # cnt가 최솟값인 res보다 클 경우도 더 탐색할 필요없으므로 백트래킹
odd = 0
for i in range(1, n + 1): # i번째 세로선에 놓인 가로선의 홀수 개수
if line[i] % 2:
odd += 1
if odd > 3 - cnt: # 홀수 개수가 더 크면 가로선을 4개 이상 추가해야 함
return
for i in range(depth, h + 1):
k = now if depth == i else 1 # 깊이가 바뀌면 1번째 세로선부터 다시 순회
for j in range(k, n):
if not ladder[i][j] and not ladder[i][j …
```
=> [BOJ] 15684 : 사다리 조작 (23.05.30)

gaeun/2023:05:30:BOJ9934.py
트리를 안 푼지 오래돼서 오랜만에 트리 문제 풀어봤습니당 !!
진짜 빠른 시일 내에 나도 골드 문제 푼다..
=> 2023/05/30 BOJ 9934 : 완전 이진 트리 [트리]

gibeom/23-05-31.py
https://www.acmicpc.net/problem/15685
``` python
dragon = [[False] * 101 for _ in range(101)] # 격자는 100 x 100
direction = [(0, 1), (-1, 0), (0, -1), (1, 0)] # index 0: x 증가, 1: y 감소, 2: x 감소, 3: y 증가
for _ in range(int(stdin.readline())):
x, y, d, g = map(int, stdin.readline().split())
dragon[y][x] = True # 드래곤 커브 시작 점
y += direction[d][0]
x += direction[d][1]
dragon[y][x] = True # 0세대 드래곤 커브 끝 점
dir = [d]
for _ in range(g): # 세대만큼 반복
for i in range(len(dir) - 1, -1, -1): # 역순으로 순회
next_d = (dir[i] + 1) % 4 # 다음 방향
y += direction[next_d][0]
x += direction[next_d][1]
dir.append(next_d) # 다음 방향 삽입
dragon[y][x] = True # i번째 세대에서 지나가는 점
square_cnt = 0
for i in range(100): # 격자 순회
for j in range(100):
if dragon[i][j] and dragon[i][j + 1] and dragon[i + 1][j] and dragon[i …
```
=> [BOJ] 15685 : 드래곤 커브 (23.05.31)

yoonjin/0601/1388.py
1. DFS 코드 암기
2. 문제풀이
- 개념이랑 코드 공부하고 문제를 봤는데 어떻게 적용해야 하는지 감이 안와서 다른 사람들 코드를 참고했다.
- 코드 암기할 때는 dfs(graph, v, visited)로 외웠는데, 문제 풀 때는 다들 dfs(x, y)로 풀더라.. 왜그런지 모르겠는데 아는 사람은 알려주세요 ~ !! ??
```
for i in [1, -1]:
yi = y + i
```
이런식으로 코드 작성해서 확인하는거 외우기 !
DFS 문제는 아직 코드 봐도 이해가 잘 안된다 .. 일단은 코드 이해될 때까지 많이 보고나서 직접 처음부터 풀어봐야겠다!
=> [23-06-01] BOJ 1388 (DFS)

gibeom/23-06-03.py
https://www.acmicpc.net/problem/14501
``` python
consulting = [tuple(map(int, stdin.readline().split())) for _ in range(n)]
dp = [0] * (n + 1)
for i in range(n - 1, -1, -1): # 역순으로 순회
day, price = consulting[i]
if i + day > n: # i일의 상담 기간이 n보다 크면, 즉 퇴사해서 i일의 상담을 할 수 없으면
dp[i] = dp[i + 1] # i + 1일의 최대 수익을 기록
else:  # i일의 상담을 할 수 있으면
dp[i] = max(dp[i + day] + price, dp[i + 1]) # i일 다음 상담의 최대 수익과 i일 상담 금액의 합, i + 1일의 최대 수익 중 최댓값
print(dp[0])
```
`dp`는 i일의 최대 수익을 기록한다. 1일부터가 아닌 n일부터 역으로 순회하면서 i일의 최대 수익을 구한다. 시간 복잡도는 `O(N)`
|i|0|1|2|3|4|5|6|7|8|9|
|--|--|--|--|--|--|--|--|--|--|--|
|day|5|4|3|2|1|1|2|3|4|5|
|price|50|40|30|20|10|10|20|30|40|50|
- i == 9 or i == 8: **퇴사해서 상담 불가**
|i|0|1|2|3|4|5|6|7|8|9|10|
|--|--|--|--|--|--|--|--|--|--|--|--| …
=> [BOJ] 14501 : 퇴사 (23.06.03)

gaeun/2023:06:06:BOJ16926.py
시간초과가 발생하여 실패했다.
첫번째 코드
상하좌우를 반복해가면서 순서대로 한칸씩 옮기는 방법인데, 아무래도 for문이 많아서 시간초과가 발생했던 것 같다.
`
```
import sys
n,m,k = map(int,sys.stdin.readline().split())
arr = []
line = list(map(int,sys.stdin.readline().split()))
arr.append(line)
for _ in range(k):
for mIndex in range(m//2): 
#이동할 노드
node = arr[mIndex][m-mIndex-1]
for l in range(m-mIndex-1,mIndex,-1):
if l == mIndex :
node = arr[mIndex][l]
break
nextNode = arr[mIndex][l-1]
arr[mIndex][l-1] = node
node = nextNode
for d in range(mIndex,n-mIndex):
if d == n-mIndex-1:
break
nextNode = arr[d+1][mIndex]
arr[d+1][mIndex] = node
node = nextNode
for r in range(mIndex,m-mIndex):
if r == m-mIndex-1:
break
nextNode = arr[n-mIndex-1][r+1]
arr[n-mIndex-1][r+1] = node
node = nextNode
for u in range(n-mIndex-1,mIndex,-1):
if u == mIndex …
```
=> 2023/06/06 BOJ 16929 : 배열 돌리기 1[구현]

gibeom/23-06-10.py
https://www.acmicpc.net/problem/14890
인덱스를 고려하면서 주어진 조건을 충족시키면 크게 어렵지 않게 해결할 수 있는 문제
``` python
def can_move(road):
slope = [False] * N # 경사로
i = 1
while i < N:
if abs(road[i - 1] - road[i]) > 1: # 전 칸 높이와 현재 칸 높이의 차이가 2 이상일 경우
return False
if road[i - 1] > road[i]: # 전 칸 높이가 더 클 경우 현재 칸부터 앞으로 경사로를 놓을 수 있는지 확인
for j in range(i, i + L): # 경사로의 길이는 L이고 현재 칸부터 경사로를 놓으므로 i ~ i + L - 1까지 확인
if j >= N or road[j] != road[i]: # 길의 범위를 벗어났거나 높이가 모두 같지 않을 경우
return False
slope[j] = True # 경사로를 놓을 수 있으면 해당 index True 처리
i += L # for문을 다 돌면 L길이의 경사로를 놓았다는 얘기이므로 i + L칸부터 확인
elif road[i - 1] < road[i]: # 현재 칸 높이가 더 클 경우 전 칸부터 뒤로 경사로를 놓을 수 있는지 확인
if slope[i - L]: # 놓을 경사로 범위에 이미 경사로가 놓아져 있을 경우 (맨 끝만 확인하면 됨)
return False
for j in range(i - L, i - 1):
if j < 0 or road[j] != road[i - …
```
=> [BOJ] 14890 : 경사로 (23.06.10)

gaeun/2023:06:12:BOJ21314.py
https://www.acmicpc.net/problem/21314
구현 문제 !
구현 문제가 약한거 같아서 차근차근 풀어봤습니다 ~
최대한 중복되는 작업을 줄이려고 노력해 봤어요 ~!
```
num = list(map(str,input()))
minValue = []
maxValue = []
mcount = 0
for ind,i in enumerate(num) :
if i == 'M': # 받은 문자가 M일때
mcount +=1
if ind == len(num)-1 :
#마지막에 K 없이 M으로 끝나는 경우
maxValue.append('1'*mcount)
minValue.append(str(10**(mcount-1))) 
else : # 받은 문자가 K일때
if mcount == 0 :
maxValue.append('5')
minValue.append('5')
else :
#최댓값
maxValue.append(str((10**mcount)*5))
#최솟값
minValue.append(str(10**(mcount-1)))
minValue.append('5')
mcount = 0
print(''.join(map(str,maxValue)))
print(''.join(map(str,minValue)))
```
=> 2023/06/12 BOJ 21314 : 민겸 수 [구현]

gibeom/23-06-12.py
https://www.acmicpc.net/problem/16235
`PyPy3`로 통과했다. 시간 제한이 빡빡해서 시간을 최대한 줄이는 것이 관건인 문제였는데 시간 초과가 계속 발생했다.
처음엔 `heapq`를 썼지만 삽입, 삭제마다 `O(logN)`의 시간복잡도를 가지기 때문에 실패
deque를 쓰고 새로 번식하는 나무를 왼쪽에서 append하는 식으로 변경 -> 정렬할 필요가 없어지므로 시간을 줄일 수 있다.
> deque의 삽입, 삭제 시간복잡도는 `O(1)`
``` python
def spring_summer_winter():
for r in range(n):
for c in range(n):
dead_tree = 0
for _ in range(len(tree[r][c])):
age = tree[r][c].popleft()
if nutrient[r][c] >= age: # 봄 : 양분이 나무의 나이보다 크거나 같으면
nutrient[r][c] -= age # 나이만큼 양분을 먹음
tree[r][c].append(age + 1) # 한 살 증가한 나무 다시 삽입
else: # 양분이 부족하면 죽음
dead_tree += age // 2
nutrient[r][c] += dead_tree # 여름 : 죽은 나무를 양분으로 추가
nutrient[r][c] += A[r][c] # 겨울 : A[r][c]만큼 양분 추가
def fall():
tmp = []
for r in range(n):
for c in …
```
=> [BOJ] 16235 : 나무 재테크 (23.06.12)

gibeom/23-06-13.py
https://www.acmicpc.net/problem/16236
``` python
def bfs(q: deque):
visited = [[False] * n for _ in range(n)]
visited[shark_r][shark_c] = True
eatable_fish = []
min_dist = 1e9 # 먹을 수 있는 물고기 중 가장 가까운 거리
while q:
dist, r, c = q.popleft()
if dist > min_dist: # 가장 가까운 거리보다 클 경우 탐색하지 않음
continue
dist += 1
if is_out_of_range(nr, nc) or visited[nr][nc]: # 범위를 벗어났거나 이미 방문했을 경우
continue
visited[nr][nc] = True
fish = sea[nr][nc]
if 0 < fish < shark_size: # 먹을 수 있는 물고기일 경우
eatable_fish.append((dist, nr, nc)) # 물고기 삽입
min_dist = min(dist, min_dist) # 최소 거리 갱신
elif not fish or fish == shark_size: # 물고기가 상어의 크기와 같거나 물고기가 없는 칸일 경우
q.append((dist, nr, nc)) # bfs
if eatable_fish: # 먹을 수 …
```
=> [BOJ] 16236 : 아기 상어 (23.06.13)

yoonjin/0613/1931.py
[1931](https://www.acmicpc.net/problem/1931)
---
푸는 방식 잘 생각해내면 풀이는 잘 되는데,
lambda를 자주 사용하지 않아서 적용하기가 힘들었다.
=> [23-06-13] BOJ 1931

yoonjin/0614/2606.py
[2606](https://www.acmicpc.net/problem/2606)
---
dfs로 풀었는데, bfs로도 다시 풀어봐야겠다.
=> [23-06-14] BOJ 2606

gibeom/23-06-14.py
https://www.acmicpc.net/problem/17140
``` python
from collections import Counter
def sort(array):
res, max_len = [], 0
for arr in array:
counter = Counter(arr) # {수 : 등장 횟수, ...}와 같은 dictionary로 반환
counter.pop(0, None) # key = 0 제거
row = sorted(counter.items(), key=lambda x: (x[1], x[0])) # 등장 횟수로 오름차순 정렬 후 수의 크기로 오름차순 정렬
row = list(sum(row, ())) # [(1, 2), (3, 4), ...]의 형태이기 때문에 [1, 2, 3, 4, ...]으로 변환
if len(row) > 100: # 행의 길이가 100보다 크면 slicing
row = row[:100]
max_len = max(max_len, len(row)) # 행의 최대 길이 갱신
res.append(row)
return fill_zero(max_len, res)
def fill_zero(max_len, res):
for row in res:
if len(row) < max_len: # 최대 길이보다 작은 행은 차이만큼 0으로 채움
row.extend([0] * (max_len - len(row)))
return res
r, c, k = map(int, stdin.readline().split())
array = [list(map(int, …
```
=> [BOJ] 17140 : 이차원 배열과 연산 (23.06.14)

yoonjin/0615/2667.py
[2667](https://www.acmicpc.net/problem/2667)
``` python
graph = []
result = []
count = 0
#입력받기
graph.append(list(map(int,input())))
#방향 전환
dx = [0,0,1,-1]
dy = [1,-1,0,0]
def dfs(x,y):
global count
if x<0 or x>=n or y<0 or y>=n:
return
if graph[x][y] == 1:
count += 1
graph[x][y] = 0
for i in range(4): #상하좌우 이동
nx = x + dx[i]
ny = y + dy[i]
dfs(nx,ny)
for j in range(n):
if graph[i][j] == 1:
dfs(i,j)
result.append(count)
count = 0
result.sort()
print(len(result))
for i in result:
print(i)
```
- 31332KB
- 44ms
dfs 상하좌우 이동하는 문제 풀었다. 내일은 다른 사람들 코드 참고 안하고 풀어봐야지!
=> [23-06-15] BOJ 2667

gibeom/23-06-16 (1).py, gibeom/23-06-16 (2).py, gibeom/23-06-16 (3).py
[1149](https://www.acmicpc.net/problem/1149)
[1629](https://www.acmicpc.net/problem/1629)
[1932](https://www.acmicpc.net/problem/1932)
``` python
house = [list(map(int, stdin.readline().split())) for _ in range(n)]
for i in range(1, n): # 전 집의 색과 달라야 하므로 전 집의 다른 두 색깔 중 최솟값을 더해준다
house[i][0] += min(house[i - 1][1], house[i - 1][2])
house[i][1] += min(house[i - 1][0], house[i - 1][2])
house[i][2] += min(house[i - 1][0], house[i - 1][1])
print(min(house[-1]))
```
<br>
``` python
def pow(n, k):
if k == 1:
return n % c
tmp = pow(n, k // 2)
if k % 2 == 1: # 지수가 홀수일 경우
return n * tmp * tmp % c  # 이전 재귀 값^2 * 밑
else: # 지수가 짝수일 경우
return tmp * tmp % c # 이전 재귀 값^2
a, b, c = map(int, stdin.readline().split())
print(pow(a, b))
``` …
=> [BOJ] 1149 : RGB 거리, 1629 : 곱셈, 1932 : 정수 삼각형 (23.06.16)

yoonjin/1012/1012.py
[#1012](https://www.acmicpc.net/problem/1012)
``` python
import sys
sys.setrecursionlimit(10000)
def dfs(x,y):
#상하좌우 확인
dx = [1, -1, 0, 0]
dy = [0, 0, 1, -1]
nx = x + dx[i]
ny = y + dy[i]
if (0 <= nx < n) and (0 <= ny < m): #범위 확인
if graph[nx][ny] == 1: #1인 경우 dfs 재귀 실행
graph[nx][ny] = 0
dfs(nx,ny)
#입력받기
t = int(input())
for i in range(t):
m,n,k = map(int,input().split())
graph = [[0]*m for _ in range(n)]
cnt = 0
for i in range(k):
a, b = map(int, input().split())
graph[b][a] = 1 #처음에 여기 graph[a][b]로 했다가 틀림
for j in range(m):
#1인 경우 dfs 실행
if graph[i][j] == 1:
dfs(i,j)
cnt += 1 
print(cnt)
```
- {31652}KB
- {312}ms
오늘도 이어서 dfs 문제를 풀었다 !
처음에 graph[b][a] = 1 부분을 graph[a][b]로 해서 틀렸다. 행열 위치 똑바로 잘 확인해야겠다 !
그러고 나서 런타임에러 뜨길래 다른 사람들 코드 …
=> [23-06-16] BOJ 1012

gibeom/23-06-17.py
[1916](https://www.acmicpc.net/problem/1916)
``` python
from heapq import heappop, heappush
def dijkstra(start):
q = []
heappush(q, (0, start)) # 최소 힙
while q:
dist, now = heappop(q)
if now == end: # 현재 도시가 도착 도시이면 while문 탈출
break
for next, next_dist in city[now].items(): # 현재 도시에서 가는 다음 도시 순회
next_dist += dist # 현재 도시까지 온 거리 + 현재 도시에서 다음 도시로 가는 거리
if next_dist < distance[next]: # 다음 도시에 저장된 거리보다 작으면
distance[next] = next_dist # 최솟값 변경
heappush(q, (next_dist, next)) # 다음 도시 queue에 삽입
n, m = int(stdin.readline()), int(stdin.readline())
city = [{} for _ in range(n + 1)]  # [{도착 도시: 비용, ...}, {...}, ...] 식으로 저장
for _ in range(m):
a, b, cost = map(int, stdin.readline().split())
if b in city[a]:
city[a][b] = min(city[a][b], cost) # 중복된 버스가 존재하기 때문에 최솟값 저장
else:
city[a][b] …
```
=> [BOJ] 1916 : 최소비용 구하기 (23.06.17)

gibeom/23-06-20.py
#65
``` python
def move_cloud(move_r, move_c) -> set:
moved_cloud = set() # 이동한 구름
while cloud:
r, c = cloud.popleft()
r, c = (r + move_r) % n, (c + move_c) % n # 양 끝이 연결되어 있으므로 n으로 나눈 나머지를 구함
board[r][c] += 1 # 물의 양 1 증가
moved_cloud.add((r, c)) # 이동한 구름에 삽입
return moved_cloud
def copy_diagonal(moved_cloud: set):
for r, c in moved_cloud:
cnt = 0
for d in range(1, 8, 2): # 대각선 방향만 순회
nr, nc = r + direction[d][0], c + direction[d][1]
if 0 <= nr < n and 0 <= nc < n and board[nr][nc]: # 범위 내이고 물이 있을 경우
cnt += 1
board[r][c] += cnt # 대각선 방향 1 거리에 물이 있는 바구니 개수만큼 물의 양 증가
def create_cloud(moved_cloud: set):
for j in range(n):
if board[i][j] < 2 or (i, j) in moved_cloud: # 물의 양이 2 미만이거나 이미 이동했던 구름일 경우
continue
cloud.append((i, …
```
=> [BOJ] 21610 : 마법사 상어와 비바라기 (23.06.20)

yoonjin/0620/21610.py
#65
[BOJ 21610](https://www.acmicpc.net/problem/21610)
첫번째 풀이
``` python
a = [list(map(int, stdin.readline().split())) for _ in range(n)]
move = [list(map(int, stdin.readline().split())) for _ in range(m)]
dx = [0,-1,-1,-1,0,1,1,1]
dy = [-1,-1,0,1,1,1,0,-1]
ddx = [1,1,-1,-1]
ddy = [1,-1,1,-1]
#구름이 있는지 확인
clouds_exist = [[False]*n for _ in range(n)]
clouds = [[n-1,0],[n-1,1],[n-2,0],[n-2,1]]
move_cloud = []
for d,s in move:
for i in range(len(clouds)):
x = clouds[i][0] + dx[d-1]*s
y = clouds[i][1] + dy[d-1]*s
x %= n
y %= n
a[x][y] += 1
clouds[i] = [x,y]
clouds_exist[x][y] = True
#구름 모두 사라짐
clouds = []
count = 0
#경계를 넘지 않는 경우
if(0 <= x+ddx[i] < n and 0 <= y+ddy[i] < n and a[x+ddx[i]][y+ddy[i]] >= 1):
count += …
```
=> [23-06-20] BOJ 21610

2023:06:20 BOJ21610.py, gaeun/2023:06:16:BOJ15686.py
#65
``` python
import sys
n,m = map(int,sys.stdin.readline().split())
#
baskets = []
#이동 정보 [방향, 이동거리]
move = []
newCloud = [[n-2,0],[n-2,1],[n-1,0],[n-1,1]]
dx = [0,-1,-1,0,1,1,1,0,-1]
dy = [0,0,-1,-1,-1,0,+1,1,1]
ax = [-1,-1,1,1]
ay = [-1,+1,-1,1]
def moveCloud(d,s,flag):
global visited
global newCloud
cloud = newCloud
#구름 이동
for c in range(len(cloud)) :
cloud[c][0] = (cloud[c][0] + (dy[d]*s)) % n
cloud[c][1] = (cloud[c][1] + (dx[d]*s)) % n
cx = cloud[c][0]
cy = cloud[c][1]
visited[cx][cy] = True
#비를 뿌려준다.
baskets[cx][cy] +=1
#대각선 구름 찾기
for c in cloud :
x = c[0]
y = c[1]
count = 0
if -1 < x+ax[i] < n and -1 < y+ay[i] < n :
if baskets[x+ax[i]][y+ay[i]] > 0 :
count+=1
baskets[x][y] += count
sumWater = 0
newCloud=[]
#다른 구름들을 찾는다
for ix in range(n) :
for iy in range(n) : …
```
=> 2023/06/20 BOJ 21610 마법사 상어와 비바라기 [구현]

gibeom/23-06-21.py
#68
``` python
from itertools import combinations
house = []
chicken = []
city = list(map(int, stdin.readline().split()))
for j in range(n):
if city[j] == 1:
house.append((i, j)) # 집 index
elif city[j] == 2:
chicken.append((i, j)) # 치킨집 index
res = 1e9
for chicken_pick in combinations(chicken, m): # 치킨집에서 m개를 뽑는 조합
total_chicken_dist = 0
for hr, hc in house:
chicken_dist = 1e9
for cr, cc in chicken_pick:
chicken_dist = min(chicken_dist, abs(hr - cr) + abs(hc - cc)) # 한 집마다 치킨 거리를 구함
total_chicken_dist += chicken_dist # 도시의 치킨 거리는 모든 집의 치킨 거리의 합
res = min(res, total_chicken_dist) # 도시의 치킨 거리의 최솟값을 구함
print(res)
```
- 31256KB
- 612ms
두 달전에 풀었던 문제였음에도 새롭게 느껴졌는데 다 풀고 비교해보니까 똑같이 풀었다 #13
=> [BOJ] 15686 : 치킨 배달 (23.06.21)

gibeom/23-06-22.py
#72 
``` python
def check_button(limit, next):
move_cnt = res
channel = 100 # 100번 채널부터 1 또는 -1씩 채널 이동할 것
while channel != limit:
for num in str(channel): # 현재 채널 숫자 확인
if num in broken: # 고장난 숫자가 포함되었을 경우 탈출
break
else: # 고장난 숫자가 없을 경우
move_cnt = min(move_cnt, len(str(channel)) + abs(channel - n)) # 이동 횟수 최솟값 갱신
channel += next # 채널 이동
return move_cnt
n, m = int(stdin.readline()), int(stdin.readline())
broken = set(stdin.readline().split())
res = abs(n - 100) # + 또는 - 버튼으로만 이동한 횟수
if n == 100: # 현재 보고 있는 채널과 같을 경우
print(0)
elif m == 0: # 고장난 버튼이 없을 경우
print(min(res, len(str(n)))) # + 또는 -버튼으로만 이동하거나 숫자 버튼으로 이동
elif m == 10: # 0 ~ 9 버튼이 모두 고장났을 경우
print(res)
else:
if 100 < n: # 100보다 큰 채널로 이동할 경우
print(min(res, check_button(1000001, 1))) # 채널은 무한이기 때문에 limit을 설정하지 …
```
=> [BOJ] 1107 : 리모컨 (23.06.22)

yoonjin/0622/1107.py
#72  
1차
``` python
import sys
m = int(input())
number = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
wrong = list(map(int, input().split()))
for i in wrong:
number.remove(i)
target = list(map(int,str(n)))
count = 0
for i in range(len(target)):
if target[i] not in number:
min = 1e9
near_num = 0
for j in number:
if min > abs(j - target[i]):
min = abs(j - target[i])
target[i] = j
count += 1
target_num = ''.join(map(str, target))
target_num = int(target_num)
count = count + abs(target_num - n)
print(count)
```
2차
``` python
import sys
m = int(input())
wrong = list(map(int, input().split()))
count = abs(100 - n)
for nums in range(1000001):
nums = str(nums)
for j in range(len(nums)):
if int(nums[j]) in wrong:
break
elif …
```
=> [23-06-22] BOJ 1107

gaeun/2023:06:22 BOJ1107.py
#72
``` python
import sys
buttonStatus = [ True for i in range(10) ]
#희망하는 채널
num = int(sys.stdin.readline())
#위,아래 버튼만으로 조작
upDownCount = abs(num-100)
#고장난 버튼 수
brokenBttCount = int(sys.stdin.readline())
#고장난 버튼 리스트
if brokenBttCount > 0 :
brokenBtts = list(map(int,sys.stdin.readline().split()))
else :
print(min(upDownCount,len(str(num))))
exit()
#고장난 버튼 False로 변경
for i in brokenBtts :
buttonStatus[i] = False
#100000번까지 숫자를 만들어, +,-로 num 채널까지 이동
for i in range(1000001):
numStr = str(i)
for j in range(len(numStr)):
if not buttonStatus[int(numStr[j])] :
break
elif j == len(numStr) -1:
upDownCount = min(upDownCount,abs(num-i)+len(numStr))
print(upDownCount)
```
- 31388 KB
- 2288 ms
*프로그래머스 문제일 경우 테스트 결과 캡쳐본을 넣어주세요*
예전에 풀었던 문제라서 쉽게 풀 수 있었습니다
=> 2023/06/22 BOJ 1107 리모컨 [구현]

yoonjin/0623/1987.py
#76 
``` python
#1차
import sys
r, c = map(int, input().split())
board = [list(input()) for _ in range(r)]
answer = 0
def dfs(x, y, before):
global answer
dx = [0,0,-1,1]
dy = [1,-1,0,0]
nx = x + dx[i]
ny = y + dy[i]
if (0 <= nx < r and 0 <= ny < c and board[nx][ny] not in before):
dfs(nx, ny, before + board[nx][ny])
if(len(before) > answer):
answer = len(before)
dfs(0,0,board[0][0])
print(answer)
```
*이렇게 풀었을 때 pypy로 제출했는데도 시간 초과가 떴다.
``` python
#2차
import sys
r, c = map(int, input().split())
board = [list(map(lambda x:ord(x)-65, input())) for _ in range(r)]
visited = [False] * 26
answer = 1
d = [(1,0), (-1,0), (0,1), (0,-1)]
def dfs(x, y, cnt):
global answer
answer = max(answer, cnt)
#방향 전환
nx, ny …
```
=> [23-06-24] BOJ 1987

gaeun/2023:06:26 BOJ20055.py
#79 컨베이어 벨트 위의 로봇 
``` python
n,k = map(int,input().split())
aArray = list(map(int,input().split()))
zeroCount = aArray.count(0)
#로봇 위치
robbotArray = [False for _ in range(n)]
robbotQ = deque(robbotArray)
#벨트 내구도
queue = deque(aArray)
i = 0
while zeroCount < k  :
i +=1
lastBelt = queue.pop()
queue.appendleft(lastBelt)
lastrobbot = robbotQ.pop()
robbotQ.appendleft(False)
#로봇 이동
for r in range(len(robbotQ)-1,0,-1) :
#n번째 로봇이 있으면 내리기
if r == n-1 :
robbotQ[r] = False
elif robbotQ[r] and (queue[r+1] > 0) and robbotQ[r+1]==False  :
queue[r+1]-=1
robbotQ[r]= False
robbotQ[r+1] = True
if queue[r+1] == 0 :
zeroCount +=1
#로봇 올리기
if queue[0] > 0  and robbotQ[0] == False :
robbotQ[0] = True
queue[0] -=1
if queue[0] == 0 :
zeroCount +=1
print(i)
```
*추가적으로 설명할 부분은 여기에 …
=> 2023/06/26 BOJ 20055 : 컨베이어 벨트 위의 로봇 [구현]

yoonjin/0626/20055.py
#79 
``` python
import sys
N, K = map(int, input().split())
A = deque(list(map(int, input().split())))
robot = deque([0] * N) #로봇 있으면 1, 없으면 0
result = 0
while True:
A.rotate(1)
robot.rotate(1)
robot[-1] = 0
if robot:
for i in range(N-2, -1, -1):
if robot[i] == 1 and robot[i+1] == 0 and A[i+1] >= 1:
robot[i+1] = 1
robot[i] = 0
A[i+1] -= 1
robot[-1] = 0
if robot[0] == 0 and A[0] >= 1:
robot[0] = 1
A[0] -= 1
#내구도가 0인 칸의 개수가 k개 이상이면 종료
if A.count(0) >= K:
break
result += 1
print(result)
```
- 34144KB
- 3112ms
처음에 읽자마자 문제가 이해되지는 않았는데 차근차근 읽어보니까 괜찮았다. 벨트가 2n짜리인게 헷갈렸지만 결국 n까지만 생각하면 되는 것 같다. deque.rotate()만 잘 알고 있었다면 접근할 수 있었을 것 같다.
회전 나오면 deque.rotate() 떠올리기
deque.rotate(숫자) 사용하면 숫자만큼 …
=> [23-06-26] BOJ 20055

yoonjin/0627/14888.py
#83 
``` python
import sys
from itertools import permutations
numbers = list(map(int, input().split()))
operators = list(map(int, input().split()))
op = list()
#operators 변환
for i in range(operators[0]):
op.append('+')
for i in range(operators[1]):
op.append('-')
for i in range(operators[2]):
op.append('*')
for i in range(operators[3]):
op.append('/')
total_max = -1e9
total_min = 1e9
for op_case in permutations(op, len(op)):
total = numbers[0]
for i in range(1, n):
if op_case[i-1] == '+':
total += numbers[i]
elif op_case[i-1] == '-':
total -= numbers[i]
elif op_case[i-1] == '*':
total *= numbers[i]
elif op_case[i-1] == "/":
total = int(total / numbers[i])
if total_max < total:
total_max = total
if total_min > total:
total_min = total …
```
=> [23-06-27] BOJ 14888

gaeun/2023:06:27 BOJ14888.py
#83 
``` python
nums = list(map(int,input().split()))
opt = list(map(int,input().split()))
minValue = int(1e9)
maxValue = int(-1e9)
def dfs(ind,status):
global minValue,maxValue,opt
if ind == n :
minValue = min(minValue,status)
maxValue = max(maxValue,status)
else :
if opt[0] >0 :
opt[0]-=1
dfs(ind+1,status+nums[ind])
opt[0]+=1
if opt[1] >0:
opt[1]-=1
dfs(ind+1,status-nums[ind])
opt[1]+=1
if opt[2]>0 :
opt[2]-=1
dfs(ind+1,status*nums[ind])
opt[2]+=1
if opt[3]>0 :
opt[3]-=1
if status < 0 :
dfs(ind+1,(abs(status)//nums[ind])*-1)   
else :
dfs(ind+1,status//nums[ind])
opt[3]+=1
dfs(1,nums[0])
print(maxValue)
print(minValue)
```
minValue와 maxValue 값을 int형으로 지정해주지 않아서 43%에서 계속 틀렸었다 ㅠㅠ (기범님 감사합니다 *^^*)
- 31256 KB
- 68 ms
*프로그래머스 …
=> 2023/06/27 BOJ 14888 연산자 끼워넣기 [브루트포스,백트래킹]

yoonjin/0629/14503.py, yoonjin/0629/1967.py
#87 
``` python
import sys
sys.setrecursionlimit(10**9)
tree = [[] for _ in range(n+1)]
for _ in range(n-1):
parent, child, weight = map(int, input().split())
tree[parent].append((child, weight))
tree[child].append((parent, weight))
def dfs(x, weight):
for node, w in tree[x]:
cal_w = weight + w
if visited[node] == -1:
visited[node] = cal_w
dfs(node, cal_w)
return
visited = [-1]*(n+1)
visited[1] = 0
dfs(1,0)
idx, tmp = 0, 0
for i in range(1, len(visited)):
if visited[i] > tmp:
tmp = visited[i]
idx = i
visited = [-1]*(n+1)
visited[idx] = 0
dfs(idx, 0)
print(max(visited))
```
- 35812KB
- 84ms
다른 코드 이해하기도 조금 어려웠다 .. 아직 잘 이해를 못한 것 같다 ㅜ 다시 더 찾아봐야 할듯 ..
---
#89 
``` python
import sys
input = …
```
=> [23-06-28,29] BOJ 1967, 14503

gibeom/23-06-29.py
#89
``` python
r, c, d = map(int, stdin.readline().split())
room = [stdin.readline().split() for _ in range(n)]
direction = [(-1, 0), (0, 1), (1, 0), (0, -1)] # 북 동 남 서 (시계 방향)
clean_cnt = 1 # 맨 처음 주어진 r, c는 빈 칸
while True:
room[r][c] = "2" # 청소
for _ in range(4):
d = (d + 3) % 4 # 반시계 방향 회전
nr, nc = r + direction[d][0], c + direction[d][1]
if room[nr][nc] == "0": # 빈 칸이면
r, c = nr, nc # 이동
clean_cnt += 1
break # for문 탈출
else: # 빈 칸이 없으면
r, c = r - direction[d][0], c - direction[d][1] # 후진
if room[r][c] == "1": # 후진한 칸이 벽이면
break # while문 탈출
print(clean_cnt)
```
- 31256KB
- 44ms
#31 이전에 이미 풀었어서 그런지 금방 풀었다
=> [BOJ] 14503 : 로봇 청소기 (23.06.29)

gaeun/2023:06:28 BOJ1967.py, gaeun/2023:06:29 BOJ14503.py
#87 
트리의 지름
``` python
import sys
sys.setrecursionlimit(10**9)
#거리 측정
distance = [ 0 for _ in range(n+1)]
tree = [[] for _ in range(n+1)]
#트리 저장하기
for _ in range(n-1):
p , c , w = map(int,input().split())
tree[p].append((c,w))
tree[c].append((p,w))
#dfs로 탐색
def dfs(start,sumValue) : 
#start 노드의 자식 노드 찾기
nodes = tree[start]
for node in nodes :
#방문한 노드인지 확인
if distance[node[0]] == 0 :
#거리 구하기
distance[node[0]] = sumValue + node[1]
dfs(node[0],distance[node[0]])
#시작 노드 방문 표시
distance[1]= -1
#루트 노드에서 가장 먼 노드를 찾음
dfs(1,0)
firstNode = distance.index(max(distance))
distance = [ 0 for _ in range(n+1)]
distance[firstNode]= -1
#firstNode에서 가장 먼 노드를 찾는다.
dfs(firstNode,0)
print(max(distance))
```
루트 노드에서 가장 먼 노드를 우선 찾고, 찾은 노드에서 가장 먼 노드를 찾으면 트리의 지름이 된다.
- 35892 KB
- 472 ms …
=> [BOJ] 1967  & 14503 

yoonjin/0630/14719.py
#92 
``` python
import sys
h, w = map(int, input().split())
block = [[0]*w for _ in range(h)] # 블록이 없으면 0, 있으면 1, 빗물 고이면 2
height = list(map(int, input().split()))
for i in range(w):
for j in range(height[i]):
block[j][i] = 1
def check(x,y):
left_cnt = 0
right_cnt = 0
if block[x][y] == 0:
for i in range(y):
if block[x][i] == 1:
left_cnt = 1
for i in range(y+1,w):
if block[x][i] == 1:
right_cnt = 1
if left_cnt + right_cnt == 2:
block[x][y] = 2
for i in range(h):
for j in range(w):
check(i,j)
answer = 0
for i in range(h):
for j in range(w):
if block[i][j] == 2:
answer += 1
print(answer)
```
- 31648KB
- 1432ms
우하하 드디어 골드 문제를 정말 단 한줄의 검색도 없이 스스로 처음부터 끝까지 풀어서 맞았다 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
물론 코드가 깔끔해보이지는 않지만 풀었다는거에 의의를 둔다 ꕀꕀ  
내 첫 …
=> [23-06-30] BOJ 14719

gibeom/23-06-30.py
#92 
``` python
h, w = map(int, stdin.readline().split())
blocks = list(map(int, stdin.readline().split()))
res = 0
for i in range(1, w - 1): # 양쪽 끝은 빗물이 고일 수 없으므로 제외
left = max(blocks[:i]) # 현재 index 기준 왼쪽으로 가장 높은 높이
right = max(blocks[i + 1 :]) # 현재 index 기준 오른쪽으로 가장 높은 높이
max_height = min(left, right) # 둘 중 작은 높이만큼 물이 고일 수 있음
if max_height > blocks[i]: # 현재 index의 높이가 작은 경우만 물이 고일 수 있음
res += max_height - blocks[i]
print(res)
```
- 31256KB
- 44ms
=> [BOJ] 14719 : 빗물 (23.06.30)

gaeun/2023:06:30 BOJ14719.py
#92 빗물
#첫번째
``` python
#첫번째 방법
h,w = map(int,input().split())
blocks = list(map(int,input().split()))
result = 0
count = 0
start = -1
flag = False
for i in range(w) :
if start == -1 and blocks[i] == 0 :
continue
elif start == -1 and blocks[i] > 0 :
start = blocks[i]
elif start != -1 :
if blocks[i] < start :
count+=start-blocks[i]
flag = True
elif blocks[i] >= start :
if flag :
result+=count
start = blocks[i]
flag = False
else :
start = blocks[i]
print(result)
```
처음으로 풀때는 블럭을 순서대로 검토하면서 시작점을 찾고, 끝점을 찾을 때까지 더하는 방법으로 문제를 풀었다 . 하지만 이렇게 풀면 처음 시작점이 무조건 끝점보다 작을 때만 가능해서 시작점이 크고 끝점이 작은 경우는 찾지 못했다 . 그래서 재귀로도 풀어보고 다양한 방법으로 풀었는데 실패해서 결국 구글링으로 다른 사람들의 코드를 참고했다.
#두번째
``` python
h,w = map(int,input().split())
blocks = list(map(int,input().split()))
result = 0
count = 0
for i in range(1,w-1):
leftMax = …
```
=> 2023/06/30 BOJ 14719 빗물 [구현]

gaeun/2023:07:03 BOJ1918.py
#97  `ex) #1004`
``` python
medium = input()
medium = list(medium)
stack = []
result = ""
for s in medium :
if s.isalpha():
result+=s
elif s == "(":
stack.append(s)
elif s == ")" :
while stack and (stack[-1]!="("):
result +=stack.pop()
stack.pop()
elif s=="*" or s=="/" :
while stack and (stack[-1]=="*" or stack[-1]=="/"):
result +=stack.pop()
stack.append(s)
#연산자면 stack 추가
elif s=="+" or s=="-":
while stack and (stack[-1]=="*" or stack[-1]=="/") :
result +=stack.pop()
while stack and (stack[-1]=="+" or stack[-1]=="-") :
result +=stack.pop()
stack.append(s)
for _ in range(len(stack)) :
result += stack.pop()
print(result)
```
처음에는 괄호를 열고 닫는 부분 구분하는데만 stack을 이용하고 , 재귀를 이용해 최소 단위에서 계산하려고 했었음. 그런데 그렇게 하다보니 로직 구성이 힘들었음 . 1시간동안 결국 풀지 못해서 다른 풀이를 참고하려고 했지만 그땐 그 풀이를 이해 …
=> 20223/07/03 BOJ 1918 후위 표기식

gibeom/23-07-02.py, gibeom/23-07-03.py
#97
``` python
infix = stdin.readline().rstrip()
priority = {"*": 2, "/": 2, "+": 1, "-": 1} # 연산자 우선순위
stack = []
res = []
for token in infix:
if 65 <= ord(token) <= 90: # 알파벳일 경우 res에 삽입
res.append(token)
else:
if token == ")": # 닫는 괄호일 때
while stack[-1] != "(": # 여는 괄호가 아닐 때까지 
res.append(stack.pop()) # stack에서 꺼내서 res에 삽입
stack.pop() # 여는 괄호를 만나서 while문을 탈출했기 때문에 여는 괄호도 stack에서 꺼냄
elif token == "(": # 여는 괄호일 때
stack.append(token) # stack에 삽입
else:
if stack and stack[-1] != "(" and priority[stack[-1]] >= priority[token]: # 연산자일 때 연산자의 우선순위 비교
while (
stack
and stack[-1] != "("
and priority[stack[-1]] >= priority[token] # stack의 맨 위 연산자가 현재 연산자보다 우선 순위가 높으면
):
res.append(stack.pop()) # stack에서 꺼낸 후 res에 삽입
stack.append(token) # 연산자 stack에 추가
while stack: …
```
=> [BOJ] 1918 : 후위 표기식 (23.07.03)

gibeom/23-07-04.py
#100 
``` python
def sit(my_favorite):
now_r, now_c = -1, -1
max_my_favorite_cnt, max_blank_cnt = 0, 0
for r in range(n):
for c in range(n):
if classroom[r][c] != 0: # 이미 학생이 앉아있다면 건너뜀
continue
my_favorite_cnt, blank_cnt = 0, 0
for i in range(4): # 상하좌우 확인
if is_out_of_range(nr, nc): # 범위를 벗어난 경우 건너뜀
continue
if classroom[nr][nc] in my_favorite: # 좋아하는 학생이라면
my_favorite_cnt += 1
elif classroom[nr][nc] == 0: # 빈 칸이라면
blank_cnt += 1
if my_favorite_cnt > max_my_favorite_cnt: # 좋아하는 학생이 많은 칸일 경우
max_my_favorite_cnt = my_favorite_cnt
max_blank_cnt = blank_cnt
now_r = r
now_c = c
elif my_favorite_cnt == max_my_favorite_cnt and blank_cnt > max_blank_cnt: # 좋아하는 학생이 같고 빈 칸의 수가 클 경우
max_blank_cnt = blank_cnt
now_r = r
now_c = c …
```
=> [BOJ] 21608 : 상어 초등학교 (23.07.04)

gaeun/2023:07:04 BOJ21608.py
#100 
``` python
n= int(input())
students = []
room = [[0 for _ in range(n)] for _ in range(n)]
dr = [-1,0,1,0]
dc = [0,1,0,-1]
studentList = []
likeList = []
result = 0
for _ in range(n*n):
line = list(map(int,input().split()))
student = line[0]
likeStudent = line[1:]
studentList.append(student)
likeList.append(likeStudent)
like = -1
blank = 0
r,c = 0,0
for j in range(n):
like_s = 0
blank_s = 0
#비어있는 칸인지 확인
if room[i][j] == 0 :
for k in range(4) :
if -1 < dr[k]+i < n and -1 < dc[k]+j < n :
#주변 좋아하는 칸
if room[dr[k]+i][dc[k]+j] in likeStudent :
like_s +=1
#주변 빈칸
elif room[dr[k]+i][dc[k]+j] == 0 :
blank_s +=1
if like < like_s :
like = like_s
blank = blank_s
r =i
c =j
elif like == like_s :
if blank < blank_s :
blank = blank_s
r =i
c =j
room[r][c] = student
for i in …
```
=> 2023/07/04 BOJ 21608 상어초등학교 [구현]

yoonjin/0703/1918.py, yoonjin/0704/21608.py, yoonjin/0705/21608.py
#97 
#100 
1918 후위표기식
``` python
import sys
prefix = input()
op = deque()
num = deque()
op_two = deque()
num_two = deque()
for i in range(len(prefix)):
if prefix[i] == ")":
new = num.pop()
new_two = num.pop() + new # BC
new_two += op.pop() # BC+
op.pop() # 
num.append(new_two)
elif prefix[i] == "(":
op.append(prefix[i])
elif prefix[i] =="*" or prefix[i] == "/":
if prefix[i+1] == "(":
op.append(prefix[i])
else:
op.append(prefix[i])
new = num.pop()
new += prefix[i+1]
new += op.pop()
num.append(new)
elif prefix[i] == "-" or prefix[i] == "+":
op.append(prefix[i])
elif prefix[i] == "\n":
continue
elif prefix[i-1] == "*" or prefix[i-1] == "/":
continue
else:
num.append(prefix[i])
answer = num.popleft()
for i in range(len(num)):
answer += …
```
=> [23-07-03,04] BOJ 1918, 21608

gaeun/2023:07:05 BOJ1446.py
#103 
``` python
n ,d = map(int,input().split())
shortcuts = []
distances = [0]*(d+1)
shortcuts.append(list(map(int,input().split())))
for i in range(1,d+1):
distances[i]= distances[i-1]+1
for s in shortcuts :
if s[1] == i :
distances[i] = min(distances[i],distances[s[0]]+s[2])
print(distances[d])
```
0번째부터 D까지 각자의 최소 거리를 구하는 DP로 풀었다 !
- 31256 KB
- 40ms
=> 2023/07/05 BOJ 1446 지름길 [DP]

gibeom/23-07-05.py
#103
``` python
n, d = map(int, stdin.readline().split())
short_road = [tuple(map(int, stdin.readline().split())) for _ in range(n)]
dp = [1e9] * (d + 1)
dp[0] = 0
for i in range(1, d + 1):
for start, end, length in short_road: # 지름길 확인
if i == end and end - start > length: # 현재 index가 도착점과 같고, 도착점 - 시작점이 지름길보다 클 경우
dp[i] = min(dp[i], dp[start] + length) # 현재 index와 시작점 + 지름길의 최솟값
else: # 지름길이 없는 index의 경우
dp[i] = min(dp[i], dp[i - 1] + 1) # 현재 index와 이전 index + 1 의 최솟값
print(dp[-1])
```
- 31256KB
- 44ms
=> [BOJ] 1446 : 지름길 (23.07.05)

yoonjin/0705/1446.py
#103 
``` python
import sys
n, d = map(int, input().split())
graph = []
graph.append(list(map(int, input().split())))
distance = [i for i in range(d+1)]
for i in range(d+1):
distance[i] = min(distance[i], distance[i-1]+1)
for start, end, length in graph:
if i == start and end <= d and distance[i] + length < distance[end]:
distance[end] = distance[i] + length
print(distance[d])
```
- 31256KB
- 72ms
처음에 풀 때 d까지 for문을 돌면서 지름길이 더 빠른지 그냥 쭉 왔을 때가 더 빠른지 비교 해야겠다는 생각은 했는데, 이전에 지름길을 선택했을 때의 경우는 고려하지 못했다.
그래서 다른 사람들 코드를 참고한 결과 끝 지점에서 그때 그때 비교해서 갱신해놓아야 된다는 것을 알게 되었다.
=> [23-07-05] BOJ 1446

gibeom/23-07-08.py
#110
``` python
res = [0] * n
stack = []
for i, height in enumerate(map(int, stdin.readline().split())): # index, 높이 순회
if stack and stack[-1][0] < height: # 스택이 비어있지 않고 스택의 top보다 높이가 클 경우
while stack and stack[-1][0] < height: # 높이가 작을 때까지 꺼냄
stack.pop()
if stack: # 스택이 비어있지 않으면
res[i] = stack[-1][1] # 스택 top의 index 저장
stack.append((height, i + 1)) # 스택에 추가
print(" ".join(map(str, res)))
```
n이 최대 50만이라서 `O(n)`아니면 시간 초과로 풀 수 없다 스택을 그려서 풀어보면 쉽게 해결할 듯!
- 141840KB
- 552ms
현재 코드는 `[10, 9, 8, 7, ..., 11]`와 같이 높이가 역순이다가 마지막 index의 높이가 최댓값이면 마지막 index 때 while문에서 n - 1만큼 `pop()`이 일어난다. 이 때문에 `O(n)`인데 `O(n^2)`인 줄 착각했고, 덕분에 이런 저런 다른 방법을 시도해보면서 삽질했다
시간복잡도 계산 잘하기!
=> [BOJ] 2493 : 탑 (23.07.08)

gaeun/2023:07:07 BOJ17825.py, gaeun/2023:07:08 BOJ2493.py
#107 `ex) #1004`
``` python
def go(cnt, rlt):
global ans
if cnt == 10:
ans = max(ans, rlt)
return
#중복순열 : 말 4개
graph, pos = H[i]
#다음 말 위치 
nxt_graph, nxt_pos = graph, pos + D[cnt]
#다음 말 위치 초기화
#도착지점인 경우
if graph == -1:
continue
#도착지점까지 4번 코스로 경우
if graph == 4 and len(G[graph]) <= nxt_pos:
nxt_graph, nxt_pos = -1, -1
#도착지점까지 0번 코스로 경우
elif graph == 0 and len(G[graph]) + 1 <= nxt_pos:
nxt_graph, nxt_pos = -1, -1
#도착지점까지 1,2,3번 코스로 경우
elif graph in [1, 2, 3] and pos == len(G[graph]) - 1 and D[cnt] == 5:
nxt_graph, nxt_pos = -1, -1
else:
#다른 코스로 이동하는 경우
if graph == 0 and (nxt_pos in [5, 10, 15, 20]):
if nxt_pos == 5:
nxt_graph = 1
nxt_pos = 0
elif nxt_pos == 10:
nxt_graph = 2
nxt_pos = 0
elif nxt_pos == 15:
nxt_graph = 3
nxt_pos = 0
else:
nxt_graph = 4
nxt_pos = 3
elif …
```
=> 2023/07/07,08 BOJ 17825 + BOJ2493

gibeom/23-07-10.py
#113 
``` python
for _ in range(int(stdin.readline())): # 테스트 케이스만큼 순회
n = int(stdin.readline()) 
interview_rank = [0] * n
for _ in range(n): # 지원자 수만큼 순회
a, b = map(int, stdin.readline().split())
interview_rank[a - 1] = b - 1 # 서류 성적 순위를 index
min_interview_rank = interview_rank[0] # 서류 성적 1위의 면접 성적 순위
cnt = 1 # 서류 성적 1위는 무조건 뽑음
for rank in interview_rank[1:]: # 서류 성적 2위부터 순회
if min_interview_rank > rank: # 마지막에 뽑힌 지원자의 면접 성적 순위와 비교
min_interview_rank = rank
cnt += 1
print(cnt)
```
서류 성적 순위로 정렬한 후 면접 성적 순위만 비교하면 된다 (동석차 없음)
서류 성적 순위로 정렬했을 때 현재 index는 이전 index보다 무조건 서류 성적이 낮기 때문에 면접 성적이 높아야 한다.
ex) 서류 성적 순위로 정렬 후 면접 성적 순위가 `[7, 6, 4, 8, 3, 5, 2, 1]`와 같을 때 7, 6, 4, 3, 2, 1만 뽑힌다
- 35892KB
- 2216ms
=> [BOJ] 1946 : 신입 사원 (23.07.10)

gaeun/2023:07:10 BOJ1946.py
#113 
``` python
import sys
t = int(sys.stdin.readline())
result = []
for _ in range(t):
NumList = []
NumList.append(list(map(int,sys.stdin.readline().split())))
NumList.sort()
target = NumList[0]
count = 1
for arr in NumList[1:] :
if arr[1] < target[1] :
count+=1
target = arr
result.append(count)
for i in range(len(result)):
print(result[i])
```
처음에 쉬울 줄 알았는데, 감이 잡힐 거 같으면서도 명확하게 잡히지 않았다.  특히 그리디와 dp를 명확하게 잘 못 푸는 것 같다 조금 더 연습이 필요함
- 51252 KB
- 4820 ms
=> 2023/07/10 BOJ 1946 신입사원 [그리디]

yoonjin/0711/17779.py
#118 
``` python
import sys
A = []
A.append(list(map(int, input().split())))
def calculate(r,c,d1,d2):
board = [[0]*(n+1) for i in range(n+1)]
for i in range(d1+1):
board[r+i][c-i] = 5
board[r+d2+i][c+d2-i] = 5
for i in range(d2+1):
board[r+i][c+i] = 5
board[r+d1+i][c-d1+i] = 5
for i in range(r+1, r+d1+d2):
flag = False
for j in range(1, n+1):
if board[i][j] == 5:
flag = not flag
if flag:
board[i][j] = 5
for x in range(1,n+1):
for y in range(1,n+1):
if x < r+d1 and y <= c and board[x][y] == 0:
board[x][y] = 1
elif x <= r + d2 and c < y and board[x][y] == 0:
board[x][y] = 2
elif r+d1 <= x and y < c-d1+d2 and board[x][y] == 0:
board[x][y] = 3
elif r+d2 < x and c-d1+d2 <= y and board[x][y] == 0:
board[x][y] = 4
count = [0 for i …
```
=> [23-07-11] BOJ (17779)

gaeun/2023:07:11 BOJ17779.py
#118 
``` python
def findScope(x,y,d1,d2):
global minValue
for d1Ind in range(0,d1+1):
#1번 경계선
if scope[y-d1Ind][x+d1Ind] != -1 :
scope[y-d1Ind][x+d1Ind] = -1
sumPeople[4]+=city[y-d1Ind][x+d1Ind]
#4번 경계선
if  scope[y+d2-d1Ind][x+d2+d1Ind] != -1 :
scope[y+d2-d1Ind][x+d2+d1Ind] = -1
sumPeople[4]+=city[y+d2-d1Ind][x+d2+d1Ind]
for d2Ind in range(0,d2+1):
#2번 경계선
if scope[y+d2Ind][x+d2Ind] != -1 :
scope[y+d2Ind][x+d2Ind] = -1
sumPeople[4]+=city[y+d2Ind][x+d2Ind]
#3번 경계선
if scope[y-d1+d2Ind][x+d1+d2Ind] != -1 :
scope[y-d1+d2Ind][x+d1+d2Ind] = -1
sumPeople[4]+=city[y-d1+d2Ind][x+d1+d2Ind]
for r in range(n):
#경계선이 없는 구역
if not -1 in scope[r] :
for c in range(n):
if r< y-d1 and c <=x+d1 :
scope[r][c]=1
sumPeople[0]+=city[r][c]
elif r< y-d1 and c > x+d1 :
scope[r][c]=2
sumPeople[1]+=city[r][c]
elif …
```
=> 2023/07/11 BOJ 17779  게리맨더링 2

gibeom/23-07-11.py
#118
``` python
def get_wards(r, c, d1, d2) -> list:
wards = [0] * 5
boundary = draw_boundary(r, c, d1, d2)
wards[0] = sum_ward(boundary, 0, r + d1, 0, c + 1, 1, 1) # 1번 선거구: (0, 0) ~ (r + d1 - 1, c), r 증가, c 증가
wards[1] = sum_ward(boundary, 0, r + d2 + 1, n - 1, c, 1, -1) # 2번 선거구: (0, n - 1) ~ (r + d2, c + 1), r 증가, c 감소 
wards[2] = sum_ward(boundary, n - 1, r + d1 - 1, 0, c - d1 + d2, -1, 1) # 3번 선거구: (n - 1, 0) ~ (r + d1, c - d1 + d2 - 1), r 감소, c 증가
wards[3] = sum_ward(boundary, n - 1, r + d2, n - 1, c - d1 + d2 - 1, -1, -1) # 4번 선거구: (n - 1, n - 1) ~ (r + d2 + 1, c - d1 + d2), r 감소, c 감소
return wards
def draw_boundary(r, c, d1, d2) -> list:
boundary = [[0] * n for _ in range(n)]
for i in range(d1 + 1):
boundary[r + i][c - i] = 1 # 1번 경계선
boundary[r + i + d2][c …
```
=> [BOJ] 17779 : 게리맨더링 2 (23.07.11)

yoonjin/0712/1092.py
#122 
``` python
import sys
crane_weight = list(map(int, input().split())) #6 8 9
crane_list = [0] * n # 0 0 0
m = int(input())
box = list(map(int, input().split())) # 2 5 2 4 7
box.sort(reverse=True) # 7 5 4 2 2
crane_weight.sort(reverse=True) # 9 8 6
error = 0
for i in range(m):
least = []
for j in range(n): # 7
if box[i] <= crane_weight[j]:
least.append(j) # 0 1
if box[i] > max(crane_weight):
error = 1
if (len(least) == 0):
minL = 1e9
minLin = 1e9
for l in range(n):
if minL > crane_list[l]:
minL = crane_list[l]
minLin = l
crane_list[minLin] += 1
else:
minK = 1e9
minKin = 1e9
for k in range(len(least)): 
if minK > crane_list[least[k]]:
minK = crane_list[least[k]]
minKin = k
crane_list[least[minKin]] += 1
if error:
print(-1)
else: …
```
=> [23-07-12] BOJ (1092)

yoonjin/0713/7490.py
#125 
``` python
import sys
from itertools import product
T = int(input())
op = ['+','-',' ']
def printAnswer(n):
line_list = [] # 정답 식들을 담을 리스트
for j in product(op, repeat=(n-1)): #j는 ['+','-',' ', ..] 리스트
stack = []
for i in range(n-1):
stack.append(i+1)
stack.append(j[i])
stack.append(n)
line = ''
for i in stack:
line += str(i)
if (eval(line.replace(' ','')) == 0): #eval 함수를 사용해서 0인지 확인
line_list.append(line)
#아스키 순서에 따라 정렬
line_list.sort()
for i in line_list:
print(i)
for i in range(T):
printAnswer(n)
print() # 문제에서 테스트 케이스 별로 한 줄 띄우라고 함
```
- 31256KB
- 168ms
풀이 과정은 쉬운데 함수들을 모르면 풀기 힘든 문제다 !
처음에는 함수를 몰라서 stack을 사용해서 풀고, ' '빈칸일 때 앞뒤 숫자를 어떻게 합쳐서 계산할지 고민하다가 실패했다.
그래서 eval함수를 찾아서 풀었다!
중복순열 함수랑 eval 함수 검색해서 풀었는데 나중에 코테 볼 때는 …
=> [23-07-13] BOJ (7490)

gibeom/23-07-13.py
#125 
``` python
def dfs(now, res, tot):
if now == n + 1: # n만큼 순회했을 때
if tot == 0: # 합이 0이면 출력
print(res)
return
if res[-1] == "1": # 1만 있으면 현재 숫자를 이어붙임
dfs(now + 1, res + " " + str(now), tot * 10 + now)
elif res[-2] != " ": # 이전 연산자가 공백이 아닐 때
operator = res[-2]
prev = int(res[-1])
if operator == "+": # +면 이전 숫자를 합에서 빼주고 현재 숫자를 이어붙여서 더함
dfs(now + 1, res + " " + str(now), (tot - prev) + (prev * 10 + now))
else: # -면 이전 숫자를 합에서 더해주고 현재 숫자를 이어붙여서 뺌
dfs(now + 1, res + " " + str(now), (tot + prev) - (prev * 10 + now))
dfs(now + 1, res + "+" + str(now), tot + now)
dfs(now + 1, res + "-" + str(now), tot - now)
for _ in range(int(stdin.readline())):
dfs(2, "1", 1)
print()
```
- 31256KB
- 44ms
아스키코드 순서에 따라 결과를 출력하라고 했으니 공백(32), +(43), -(45) 순으로 연산해야 …
=> [BOJ] 7490 : 0 만들기 (23.07.13)

gaeun/2023:07:12 BOJ1092.py, gaeun/2023:07:13 BOJ7490.py
#122 
첫번째 시도
``` python
import sys
n = int(readline())
crains = list(map(int,readline().split()))
m = int(readline())
weights = list(map(int,readline().split()))
crains.sort(reverse=True)
weights.sort(reverse=True)
weight=deque(weights)
count=0
flag = False
if weights[0] > crains[0] :
print(-1)
sys.exit()
crainBox = [0]*n
newWeight = []
minValue = 1e9
while weight :
#새로운 박스
w = weight.popleft()
nop = 0
flag = True
for c in range(len(crains)) :
#현재 크레인에 옮길 수 있는지 여부
if crains[c] >= w  :
#두번째 크레인 ~ 마지막 크레인
if minValue > crainBox[c]:
crainBox[c]+=1
minValue = crainBox[c]
flag = False
break
elif crains[c] < w :
break
if flag :
w = weight.appendleft(w)
minValue = max(crainBox)
```
박스를 가져갈 수 있는 크레인 중 하나씩 박스를 다 가졌을 때, 다음으로 박스를 가져갈 수 있는 …
=> 2023/07/12 ~ 13 BOJ 7490 0만들기 [문자열] 1092 배 [그리디]

gaeun/2023:07:14 BOJ20056.py
#128  
``` python
import sys
N,M,K = map(int,readline().split())
board = [ [ [] for _ in range(N)] for _ in range(N)]
#위 , 오른쪽 대각선
dr = [-1,-1,0,+1,+1,+1,0,-1]
dc = [0,+1,+1,+1,0,-1,-1,-1]
nextlovations = {}
def move():
global nextlovations
newLovations = {}
#파이어볼 이동
for loc in nextlovations :
r = loc[0]
c = loc[1]
for info in nextlovations[loc]:
m = info[0]
s = info[1]
d = info[2]
nextR = (r + dr[d] * s) % N 
nextC = (c + dc[d] * s) % N
if  not (nextR,nextC) in newLovations:
newLovations[(nextR,nextC)] = [[m,s,d]]
else :
newLovations[(nextR,nextC)].append([m,s,d])
nextlovations = newLovations.copy()
diviedfireball()
def diviedfireball():
newLovations = {}
global nextlovations
#중복된 파이어볼 나누기
for loc in nextlovations :
r = loc[0]
c = loc[1]
m = 0
s = 0
even = 0 …
```
=> 2023/07/14/ BOJ 20056 마법사 상어와 파이어볼 [구현]

gibeom/23-07-14.py
#128 
``` python
def move():
tmp = [[deque() for _ in range(N)] for _ in range(N)]
for r in range(N):
for c in range(N):
q = grid[r][c]
while q:
m, s, d = q.popleft()
nr = (r + direction[d][0] * s) % N
nc = (c + direction[d][1] * s) % N
tmp[nr][nc].append((m, s, d))
return tmp
def devide_fire_ball():
for r in range(N):
for c in range(N):
q = grid[r][c]
length = len(q)
if length < 2: # r, c에 파이어볼이 2개 미만이면 건너뛰기
continue
mass, speed = 0, 0 # (r, c)의 파이어볼 질량의 총합, 속력의 총합
odd, even = length, length # 모두 홀수인지 짝수인지 확인용
while q:
m, s, d = q.popleft()
mass += m
speed += s
if d % 2 == 0:
even -= 1
else:
odd -= 1
per_mass, per_speed = mass // 5, speed // length # 파이어볼 한 개당 질량, 속력
if mass // 5 == 0: # 한 개당 질량이 0이면 건너뛰기
continue
if even != 0 and odd …
```
=> [BOJ] 20056 : 마법사 상어와 파이어볼 (23.07.14)

yoonjin/0714/20056.py, yoonjin/0715/21758.py
#128
``` python
import sys
n, m, k = map(int, input().split())
fireballs =[]
for _ in range(m):
r,c,m,s,d = list(map(int, input().split()))
fireballs.append([r-1,c-1,m,s,d])
board = [[[] for _ in range(n)] for _ in range(n)]
dx = [0,1,1,1,0,-1,-1,-1]
dy = [1,1,0,-1,-1,-1,0,1]
for _ in range(k):
for r,c,m,s,d in fireballs:
nr = (r + s*dx[d]) % n #1-n번 행 연결되어 있으니까 % n
nc = (c + s*dy[d]) % n
board[nr][nc].append((m,s,d)) # r,c 위치에 m,s,d 저장
for r in range(n):
for c in range(n):
if len(board[r][c]) >= 2:
sum_m = 0 # 질량
sum_s = 0 # 속력
isEven = 0 # 짝수
isOdd = 0 # 홀수
for (m,s,d) in board[r][c]:
sum_m += m
sum_s += s
if d % 2 == 0:
isEven += 1
else:
isOdd += 1
if(isEven == len(board[r][c]) or (isOdd == len(board[r][c]))):
nd = [0,2,4,6]
else:
nd = [1,3,5,7]
if sum_m//5: …
```
=> [23-07-14,15] BOJ (20056, 21758)

gaeun/2023:07:15 BOJ21758.py
#132 꿀따기
``` python
import sys
N = int(readline())
honeyArr = list(map(int,readline().split()))
honeyBox = 0
firstBee = N -1
maxHoney = -1
sumHoneyFirst = sum(honeyArr[:firstBee])
sumHoneySecond = honeyArr[honeyBox]
for i in range(1,N-1):
maxHoney = max(maxHoney,sumHoneyFirst+sumHoneySecond-honeyArr[i])
sumHoneySecond+=honeyArr[i]
honeyBox = 1
firstBee = 0
secondBee = N -1
sumHoneyFirst = sum(honeyArr[firstBee+1:honeyBox+1])
sumHoneySecond = sum(honeyArr[honeyBox:secondBee])
for i in range(1,N-1):
maxHoney = max(maxHoney,sumHoneyFirst+sumHoneySecond)
sumHoneyFirst+=honeyArr[i+1]
sumHoneySecond-=honeyArr[i]
honeyBox = N -1
firstBee = 0
sumHoneyFirst = sum(honeyArr[firstBee+1:])
sumHoneySecond = sum(honeyArr[firstBee+2:honeyBox+1])
for i in range(1,N-1): …
```
=> 2023/7/15 BOJ 21758 꿀따기 [그리디]

yoonjin/0717/2178.py
#136 
``` python
import sys
n,m = map(int, input().split())
graph = []
graph.append(list(map(int, input().rstrip()))) # rstrip() 사용해서 맨 마지막에 '\n'제거
dx = [1,-1,0,0]
dy = [0,0,-1,1]
def bfs(x,y):
queue = deque()
queue.append((x,y))
while queue:
x, y = queue.popleft()
for i in range(4): # 4방향 갈 수 있는지 체크
nx = x + dx[i]
ny = y + dy[i]
if 0 <= nx < n and 0 <= ny < m and graph[nx][ny] == 1:
queue.append((nx,ny))
graph[nx][ny] = graph[x][y] + 1 # 지난 칸 개수 누적해서 저장
return graph[n-1][m-1] # 마지막 칸에 최소 칸 개수 나옴
print(bfs(0,0))
```
- 34128KB
- 76ms
bfs 문제를 제대로 풀어본 적이 없는 것 같아서 bfs 골랐는데 다 까먹어서 다른 코드 참고했다 ㅎㅎ
그동안 계속 dfs로만 풀었는데 bfs로도 풀어보는 습관을 가져야겠다 ~ !!
rstrip() 사용해서 맨 마지막에 '\n'제거하는거 맨날 까먹어서 검색해서 찾는다. 외워야지 !!
=> [23-07-17] BOJ 2178

gaeun/2023:07:17 BOJ2178.py
#136 로
``` python
import sys
n,m = map(int,readline().split())
maze = [[] for _ in range(n)]
visited = [[False for _ in range(m)] for _ in range(n)]
maze[i] = list(map(int,readline().strip()))
#위, 오른쪽 ,아래 , 왼쪽
dn = [-1,0,+1,0]
dm = [0,+1,0,-1]
minCount = 1e9
def bfs(nextN,nextM):
global minCount
queue = deque([[nextN,nextM,1]])
while queue :
node = queue.popleft()
nextN = node[0]
nextM = node[1]
count = node[2]
if -1 < nextN+dn[i] < n and -1 < nextM+dm[i] < m :
if nextN+dn[i] == n-1 and nextM+dm[i] == m-1 :
minCount = min(minCount,count+1)
continue
if maze[nextN+dn[i]][nextM+dm[i]] == 1 :
queue.append([nextN+dn[i],nextM+dm[i],count+1])
maze[nextN+dn[i]][nextM+dm[i]] = 0
bfs(0,0) …
```
=> 2023/07/17 2178 미로 [bfs]

yoonjin/0718/1759.py
#140 
``` python
import sys
from itertools import combinations
l,c = map(int, input().split())
words = list(input().split())
aeiou = ['a','e','i','o','u']
first = [] # 모음
second = [] # 자음
for i in words:
if i in aeiou:
first.append(i)
else:
second.append(i)
answer = []
for i in range(1,l-1):
if(i <= len(first) and (l-i) <= len(second)):
first_num = i
second_num = l-i
for first_str in combinations(first, first_num):
for second_str in combinations(second, second_num):
answer.append(first_str + second_str)
answer.sort()
for i in answer:
print(''.join(i))
```
``` python
import sys
from itertools import combinations
l,c = map(int, input().split())
words = list(input().split())
words.sort()
aeiou = ['a','e','i','o','u']
for str in …
```
=> [23-07-18] BOJ (1759)

gibeom/23-07-17.py
#136 
``` python
def bfs(x, y):
q = deque([(x, y, maze[x][y])])
while q:
r, c, cnt = q.popleft()
nr, nc = r + direction[i], c + direction[3 - i] # 상하좌우
if is_out_of_range(nr, nc):
continue
if maze[nr][nc] == 0 or maze[nr][nc] > cnt + 1: # 지나가지 않았거나 지나갔지만 현재가 더 작은 값일 경우
maze[nr][nc] = cnt + 1
q.append((nr, nc, cnt + 1))
return r < 0 or r >= n or c < 0 or c >= m or arr[r][c] == "0"
arr = [stdin.readline().rstrip() for _ in range(n)]
maze = [[0] * m for _ in range(n)]
maze[n - 1][m - 1] = 1
direction = [1, 0, -1, 0]
bfs(n - 1, m - 1)
print(maze[0][0])
```
- 34176KB
- 84ms
=> [BOJ] 2178 : 미로 탐색 (23.07.17)

yoonjin/0719/2212.py
#142 
``` python
import sys
k = int(input())
if k >= n:
print(0)
else:
sensor = list(map(int, input().split()))
sensor.sort()
mid = []
for i in range(1,n):
mid.append(sensor[i]-sensor[i-1])
mid.sort(reverse=True)
for i in range(k-1):
mid.pop(0)
print(sum(mid))
```
- 32276KB
- 48ms
문제 읽을 때는 별로 안어려워보였는데 막상 k개로 범위를 어떻게 나눠야 할지를 생각하기가 어려웠다.
막상 풀이를 보니 정말 단순했다!
다양한 사고를 해보는게 중요한 것 같다
=> [23-07-19] BOJ (2212)

gaeun/2023:07:18 BOJ1759.py, gaeun/2023:07:19 BOJ2212.py
암호 만들기
#140 
``` python
import sys
l,c = map(int,readline().split())
alphabets = list(map(str,readline().split()))
alphabets.sort()
result = []
def makePW(first):
vowel = False
consonant = 0
if alphabets[first] in ["a","e","i","o","u"] :
vowel = True
if not alphabets[first] in ["a","e","i","o","u"] :
consonant +=1
queue = deque([[alphabets[first],first,vowel,consonant]])
while queue :
info = queue.popleft()
pw = info[0]
index = info[1]
vowel = info[2]
consonant = info[3]
if len(pw) < l :
for ind in range(index+1,c) :
nextVowel = vowel
nextConsonant = consonant
if nextVowel == False and alphabets[ind] in ["a","e","i","o","u"] :
nextVowel = True
if not alphabets[ind] in ["a","e","i","o","u"] :
nextConsonant +=1 …
```
=> [BOJ] 1759 암호 만들기 & 2212 센서

yoonjin/0720/1495.py
#145 
``` python
import sys
N, S, M = map(int, input().split())
V = list(map(int, input().split()))
volume = [[0] * (M+1) for _ in range(N+1)]
volume[0][S] = 1
for i in range(N):
for j in range(M+1):
if volume[i][j] == 1:
num = j
up_volume = num + V[i]
down_volume = num - V[i]
if(0 <= up_volume <= M):
volume[i+1][up_volume] = 1
if(0 <= down_volume <= M):
volume[i+1][down_volume] = 1
end = []
for i in range(M+1):
if volume[N][i] == 1:
end.append(i)
if len(end) == 0:
print(-1)
else:
print(max(end))
```
- 31256KB
- 56ms
처음에 감을 못잡다가 그냥 전체 경우를 전부 리스트로 만들어야겠다는 아이디어를 얻은 후 잘 풀었다 ~ !!
dp를 풀 때 전체 경우를 리스트로 크게 만들어서 해당되는 경우를 표시해야겠다는 생각을 해봐야겠다 !!!!
=> [23-07-20] BOJ (1495)

gaeun/2023:07:20 BOJ1495.py
#145 
기타리스트
``` python
import sys
N,S,M = map(int,readline().strip().split())
Vol = list(map(int,readline().split()))
volumes = [[False for _ in range(M+1)] for _ in range(N+1)]
result = -1
volumes[0][S] = True
for n in range(N):
for m in range(0,M+1) :
if volumes[n][m] :
value = m + Vol[n]
if -1 < value <= M:
volumes[n+1][value] = True
value = m - Vol[n]
if -1 < value <= M:
volumes[n+1][value] = True
for ind in range(M,-1,-1):
if volumes[N][ind] :
result = ind
break
print(result)
```
처음에는 while 문을 이용해 bfs로 풀었으나 메모리초과가 났다..! 해결하려고 다른 방법을 시도했지만 그것마저 시간초과 발생 .. ㅜ
그래서 이번에는 윤진언니의 도움을 받아서 2차원 배열로 해결했다
- 34128 KB
- 76ms
*프로그래머스 문제일 경우 테스트 결과 캡쳐본을 넣어주세요*
그런데 왜 while문은 시간초과가 발생하는데 2차원 배열은 시간초과가 발생하지 않는지 아직까지 의문이다.. …
=> 2023/07/20 BOJ 1495 기타리스트 [DP]

yoonjin/0722/17142.py
#148 
``` python
import sys
N,M = map(int,input().split())
arr = [list(map(int,input().split())) for _ in range(N)]
virus_combi=[0]*M #활성 바이러스를 담을 조합
result = 10000000
def comb(cur, cnt): #조합
global result
if(cnt==M): #조합이 완성되면
result = min(result, bfs()) #작은 값을 갱신
return
for i in range(cur,len(v)):
virus_combi[cnt]=i
comb(i+1, cnt+1)
dx = [-1,1,0,0]
dy = [0,0,-1,1]
def bfs():
queue = deque()
visited = [[-1]*N for _ in range(N)] # 방문처리와 시간 계산 함께 진행
for i in virus_combi: # 활성 바이러스 조합 queue에 담아주기
queue.append([v[i][0],v[i][1]])
visited[v[i][0]][v[i][1]] = 0 # 방문처리
while queue:
cx,cy = queue.popleft() # queue에서 위치 빼옴
for d in range(4):
nx = cx+dx[d]
ny = cy+dy[d]
if(nx<0 or ny<0 or nx>=N or ny>=N or visited[nx][ny]!=-1): # 범위 체크 …
```
=> [23-07-22] BOJ 17142

gibeom/23-07-22.py
#148
``` python
from itertools import combinations
def bfs(virus, empty_cnt) -> int:
q = deque(virus)
visited = [[0] * n for _ in range(n)]
for r, c in virus: # 활성 바이러스 위치를 1초로 초기화
visited[r][c] = 1
while q:
if is_out_of_range(nr, nc): # 범위를 벗어났거나 벽이면 건너뛰기
continue
if not visited[nr][nc]: # 방문하지 않은 칸일 경우
if lab[nr][nc] == 0: # 비활성 바이러스 칸이 아닌, 빈 칸일 경우
empty_cnt -= 1 # 빈 칸 개수 1 감소
visited[nr][nc] = visited[r][c] + 1 # 현재 칸 + 1초
q.append((nr, nc))
if empty_cnt == 0: # 바이러스를 모두 퍼뜨렸을 경우
return visited[r][c] # 현재 칸의 시간을 리턴
return n**2 # 바이러스를 모두 퍼뜨리지 못했을 경우 최댓값 리턴
return 0 > r or r >= n or 0 > c or c >= n or lab[r][c] == 1
n, m = …
```
=> [BOJ] 17142 : 연구소 3 (23.07.22)

yoonjin/0724/13164.py
#151 
``` python
import sys
N, K = map(int, input().split())
students = list(map(int, input().split()))
sub = []
for i in range(1, N):
sub.append(students[i] - students[i-1])
sub.sort()
for i in range(K-1):
sub.pop()
print(sum(sub))
```
- 66736KB
- 260ms
몇일 전에 푼 문제랑 거의 똑같아서 빨리 잘 풀 수 있었다 ~ !!
뭔가 비슷한 문제 잘 푸니까 그동안 공부를 열심히 한 보람을 느낄 수 있어서 지금 기분이 좋다 ◠‿◠ 화이팅 !
=> [23-07-24] BOJ (13164)

gibeom/23-07-24.py
#151 
``` python
n, k = map(int, stdin.readline().split())
member = list(map(int, stdin.readline().split()))
differences = [member[i + 1] - member[i] for i in range(n - 1)] # 키 차이
differences.sort() # 오름차순 정렬
print(sum(differences[: n - k])) # k개 조로 나눔
```
- 66736KB
- 236ms
=> [BOJ] 13164 : 행복 유치원 (23.07.24)

gaeun/2023:07:24 BOJ13164.py
#151 행복 유치원
``` python
import sys
N,K = map(int,readline().split())
students = list(map(int,readline().split()))
minusTall = [0]*(N-1)
for s in range(len(students)):
if s == len(students)-1 :
break
minusTall[s] = students[s+1]-students[s]
minusTall.sort()
for k in range(K-1):
minusTall.pop()
print(sum(minusTall))
```
- 66736 KB
- 300ms
=> 2023/07/24 BOJ 13164 행복 유치원

yoonjin/0725/2294.py
#155 
``` python
import sys
n, k = map(int, input().split())
coins = []
coins.append(int(input()))
answer_list = [0] * (100001)
for i in coins:
answer_list[i] = 1
for i in range(len(answer_list)):
for j in coins:
if answer_list[i] != 0 and i+j < (k+1): # 배열이 넘지 않고, 도착한 적이 없을 때
if answer_list[i+j] != 0: # 도착한 적이 없을 때
answer_list[i+j] = min(answer_list[i+j],answer_list[i] + 1) # 더 작은 값으로 갱신
else:
answer_list[i+j] = answer_list[i] + 1 # 바로 이전 값 +1 로 갱신
if (answer_list[k] == 0):
print(-1)
else:
print(answer_list[k])
```
``` python
import sys
n, k = map(int, input().split())
coins = []
coins.append(int(input()))
answer_list = [100001] * (k+1)
answer_list[0] = 0
for i in coins:
for j in range(i, k+1): # …
```
=> [23-07-25] BOJ 2294

gibeom/23-07-25.py, gibeom/23-07-26.py
#155 
``` python
n, k = map(int, stdin.readline().split())
coins = set() # 가치가 같은 동전 중복 제거
coin = int(stdin.readline())
if coin <= k: # k보다 작거나 같은 동전만 삽입
coins.add(coin)
dp = [1e9] * (k + 1)
dp[0] = 0
for v in range(1, k + 1):
for coin in coins:
if v >= coin: # 동전이 현재 가치보다 작거나 같으면
dp[v] = min(dp[v], dp[v - coin] + 1) # 최솟값 갱신
print(dp[k] if dp[k] != 1e9 else -1)
```
`v - coin`가치에 현재 coin 한 개를 추가하면 `v`가치를 구할 수 있다 `dp[v - coin]` 에서는 이미 최솟값을 가지고 있기 때문에 1 더한 값과 `dp[v]`를 비교하면 된다
- 31256KB
- 368ms
=> [BOJ] 2294 : 동전 2 (23.07.25)

gaeun/2023:07:25 BOJ2294.py
#155 
``` python
import sys
N,K = map(int,readline().split())
coinType = [0]*N
dp = [1e9]* (K+1)
for i in range(N):
coinType[i] = int(readline())
dp[0] = 0
for n in range(1,K+1) :
for i in range(N):
value = n-coinType[i]
if (value) >= 0 :
dp[n] = min(dp[n],dp[value]+1)
if dp[K] == 1e9 :
print(-1)
else :
print(dp[K])
```
- 31256 KB
- 476 ms
그리디 문제인줄 알았는데, DP 문제였다...!
=> 2023/07/25 BOJ  동전2 [DP]

gaeun/2023:07:26 BOJ23288.py
#159  주사위 굴리기 2
``` python
import sys
sys.setrecursionlimit(10**7)
N,M,K = map(int,readline().split())
Map = [[]for _ in range(N)]
for n in range(N) :
Map[n] = list(map(int,readline().split()))
row = deque([4,1,3])
col = deque([2,1,5,6])
def getDice(direct):
if direct == 1 :
rowNode = row.pop()
colNode = col.pop()
col.append(rowNode)
row.appendleft(colNode)
col[1] = row[1]
elif direct == 3 :
rowNode = row.popleft()
colNode = col.pop()
row.append(colNode)
col.append(rowNode)
col[1] = row[1]
elif direct == 2 :
node = col.pop()
col.appendleft(node)
row[1] = col[1]
else :
node = col.popleft()
col.append(node)
row[1] = col[1]
def getScore(n, m,target) :
count = 1
queue = deque([[n,m]])
while queue:
info=queue.popleft()
nextN = info[0] …
```
=> 2023/07/26 BOJ 23288 주사위 굴리기2 [구현]

gibeom/23-07-26.py
#159
``` python
def bfs(r, c) -> set:
q = deque([(r, c)])
same_scores = {(r, c)} # 현재 좌표에 쓰여진 수와 같은 좌표를 담을 set 
while q:
for d in direction: # 상, 하, 좌, 우 확인
nr, nc = r + d[0], c + d[1] # 다음 좌표
if is_out_of_range(nr, nc) or (nr, nc) in same_scores: # 범위를 벗어났거나 set에 이미 있을 경우
continue
if board[nr][nc] == board[r][c]: # 현재 좌표의 쓰여진 수와 같은 좌표일 경우
q.append((nr, nc)) # 다음 탐색
same_scores.add((nr, nc)) 
return same_scores
def roll(dice, d) -> list:
top, north, east, west, south, bottom = dice
if d == 0: # 북
return [south, top, east, west, bottom, north]
elif d == 1: # 동
return [west, north, top, bottom, south, east]
elif d == 2: # 남
return [north, bottom, east, west, top, south]
else: # 서
return [east, north, bottom, top, south, …
```
=> [BOJ] 23288 : 주사위 굴리기 2 (23.07.26)

yoonjin/0727/14728.py
#162 
``` python
import sys
N, T = map(int,input().split())
subject = [0]
times = [0]
for i in range(N):
K, S = map(int, input().split())
subject.append(S)
times.append(K)
score = [[0 for _ in range(T+1)] for _ in range(N+1)]
for i in range(1, N+1):
for j in range(1, T+1):
if times[i] <= j:
score[i][j] = max(score[i-1][j], score[i-1][j-times[i]] + subject[i])
else:
score[i][j] = score[i-1][j]
print(score[N][T])
```
- 53404KB
- 660ms
처음에 풀 때는 모든 경우를 list로 만들어놓고, 과목들이 중복이 안되는데 어떻게 선택을 해야할지 모르겠어서 헤맸다.
다른 코드를 참고해보니, 과목을 한과목씩 늘릴 때마다 이전 과목의 점수를 사용해 갱신하는 식으로 풀었다.
dp 풀 때마다 바로바로 이해가 안되는걸 보니 한번 제대로 공부하는 시간이 필요할 것 같다.
=> [23-07-27] BOJ (14728)

gaeun/2023:07:27 BOJ14728.py
#162
``` python
import sys
N,T = map(int,readline().split())
study = [0] * (T+1)
for i in range(N) :
line = list(map(int,readline().split()))
for node in range(T,line[0]-1,-1) :
study[node] = max(study[node],study[node-line[0]]+line[1])
print(study[T])
```
점화식을 틀렸는지 ,, 계속 틀려서 다른 풀이 참고했습니다 !
최종 T 번째 최대값을 N번 업데이트 한다. 
- 31256 KB
- 400ms
=> 2023/07/27 BOJ 벼락치기

gibeom/23-07-29.py
#166 
``` python
n, m, r = map(int, stdin.readline().split())
array = [stdin.readline().split() for _ in range(n)]
q = deque()
result = [[0] * m for _ in range(n)]
for i in range(min(n, m) // 2):
q.extend([row[i] for row in array[i : n - i - 1]]) # 왼쪽
q.extend(array[n - i - 1][i : m - i - 1]) # 아래
q.extend([row[m - i - 1] for row in array[i + 1 : n - i][::-1]]) # 오른쪽
q.extend(array[i][i + 1 : m - i][::-1]) # 위
q.rotate(r) # 회전
for k in range(i, n - i - 1):
result[k][i] = q.popleft() # 왼쪽 채우기
for k in range(i, m - i - 1):
result[n - i - 1][k] = q.popleft() # 아래 채우기
for k in range(n - i - 1, i, -1):
result[k][m - i - 1] = q.popleft() # 오른쪽 채우기
for k in range(m - i - 1, i, -1):
result[i][k] = q.popleft() # 위 채우기
for res in result: …
```
=> [BOJ] 16926 : 배열 돌리기 1 (23.07.29)

gibeom/23-07-31.py
#168 
``` python
def move():
direction = [(0, 1), (0, -1), (-1, 0), (1, 0)]
turn_cnt = 1
while turn_cnt < 1001: # 턴이 1001보다 작을 때까지
for i in range(k): # 말 순회
r, c, d = pieces[i] # i번 말의 좌표, 방향
nr, nc = r + direction[d][0], c + direction[d][1] # 이동할 좌표
if is_out_of_range(nr, nc) or color[nr][nc] == "2": # 범위를 벗어났거나 파란색일 경우
d = d + 1 if d % 2 == 0 else d - 1 # 방향 전환
nr, nc = r + direction[d][0], c + direction[d][1] # 전환된 방향으로 이동할 좌표
pieces[i][2] = d 
if is_out_of_range(nr, nc) or color[nr][nc] == "2": # 또 범위르 벗어났거나 파란색이면 건너뛰기
continue
tmp = []
while board[r][c][-1] != i: # i번 말이 아닐 때까지 현재 좌표의 말을 꺼낸다
tmp.append(board[r][c].pop())
tmp.append(board[r][c].pop()) # i번 말도 추가
if color[nr][nc] == "0": # 이동할 좌표가 하얀색일 경우 뒤집기
tmp.reverse()
board[nr][nc].extend(tmp) # 이동할 좌표에 말 추가 …
```
=> [BOJ] 17837 : 새로운 게임 2 (23.07.31)

gaeun/2023:08:01 BOJ9251.py
#{문제 이슈번호} `ex) #1004`
``` python
import sys
first = list(readline().rstrip())
second = list(readline().rstrip())
dp = [[0 for _ in range(len(second)+1)] for _ in range(len(first)+1)]
for i in range(1,len(first)+1):
for j in range(1,len(second)+1) :
if first[i-1] == second[j-1] :
dp[i][j] = dp[i-1][j-1] + 1
else :
dp[i][j] = max(dp[i-1][j],dp[i][j-1])
print(dp[-1][-1])
```
dp말고 문자열로 풀고싶었는데,, 문자열로만 푼 풀이가 있다면 같이 공유해요 ><
-56452}KB
- 544 ms
=> 2023/08/01 BOJ 9251 LCS [DP]

gibeom/23-08-05.py
#173 
``` python
def catch(j):
for i in range(R): # 열은 낚시왕과 같은 열이고 행만 순회하면서 상어를 찾는다
if (i, j) in sharks:
return sharks.pop((i, j))[2] # 땅과 제일 가까운 상어의 사이즈 리턴
return 0 # 없으면 0
def move():
tmp_sharks = {}
for (r, c), (s, d, z) in sharks.items(): # 상어들 순회
nr, nc, d = get_next_location(r, c, s, d) # 상어의 다음 위치
if (nr, nc) in tmp_sharks and tmp_sharks[(nr, nc)][2] > z: # 다음 위치에 상어가 있고, 현재 상어보다 사이즈가 클 경우
continue
tmp_sharks[(nr, nc)] = (s, d, z) # 이외의 경우 현재 상어를 삽입
return tmp_sharks
def get_next_location(r, c, s, d):
if d < 2: # 위 또는 아래
if d == 0: # 위일 때
s += r_cycle - r # s만큼 이동했을 때 다음 r의 index
else: # 아래일 때
s += r # s만큼 이동했을 때 다음 r의 index
s %= r_cycle # row 사이클로 나눈 나머지 -> 중복 제거
if s >= R: # 범위를 벗어났을 경우
return r_cycle - s, c, 0
return s, c, 1
else:
if d == 3: # 왼쪽일 때
s += …
```
=> [BOJ] 17143 : 낚시왕 (23.08.05)

gibeom/23-08-07.py
#175 
``` python
s, t = stdin.readline().rstrip(), list(stdin.readline().rstrip())
while len(s) != len(t): # s의 길이와 t의 길이가 다를 때까지
last = t.pop() # t의 마지막 문자열 삭제
if last == "B": # B였으면 t 뒤집기
t = t[::-1]
print(1) if s == "".join(t) else print(0) # s와 t가 같으면 1, 다르면 0
```
문자열 `s`에 A 또는 B를 붙여가면서 비교하려면 두 가지 연산을 모두 실행해야 한다. 하지만 문자열 `t`의 마지막 문자열만 보면 하나의 경우의 수만 생긴다. `t`의 마지막 문자열이 A면 삭제, B면 삭제하고 뒤집는다
- 31256KB
- 40ms
=> [BOJ] 12904 : A와 B (23.08.07)

gibeom/23-08-11.py
#183 
``` python
def play():
min_len, max_len = 1e9, 0
for alpha in alphabet:
if len(alpha) < k: # k보다 개수가 적은 알파벳은 건너뜀
continue
for i in range(len(alpha) - k + 1): 
length = alpha[i + k - 1] - alpha[i] + 1 # i번째 index와 i에서 k만큼 떨어진 인덱스의 차이 -> 문자열 길이
if length < min_len: # 길이 최솟값 확인
min_len = length
if length > max_len: # 길이 최댓값 확인
max_len = length
if max_len == 0: # 알파벳이 전부 k보다 개수가 적을 경우 max_len 또는 min_len은 갱신되지 않음
print(-1)
else:
print(min_len, max_len)
t = int(stdin.readline())
for _ in range(t):
w, k = stdin.readline().rstrip(), int(stdin.readline())
alphabet = [[] for _ in range(26)] # a ~ z의 index를 담는 리스트
for j, word in enumerate(w):
i = ord(word) - 97
alphabet[i].append(j)
play()
```
- 31256KB
- 200ms
=> [BOJ] 20437 : 문자열 게임 2 (23.08.11)

gaeun/2023:08:11BOJ20437.py
#183
``` python
import sys
from collections import defaultdict
read = sys.stdin.readline
T = int(read().strip())
for t in range(T) :
W = str(read().strip())
K = int(read().strip())
dict = defaultdict(list)
for ind,w in enumerate(W):
if W.count(w) >= K :
dict[w].append(ind)
short = 1e9
long = -1
for w, itemList in dict.items() :
if len(itemList)==K :
first = itemList[0]
last = itemList[len(itemList)-1]
stringSize = last-first+1
if stringSize < short :
short = stringSize
if stringSize > long :
long = stringSize
elif len(itemList) >=K :
for i in range(len(itemList)-K+1):
first = itemList[i]
last = itemList[i+K-1]
stringSize = last-first+1
if stringSize < short :
short = stringSize
if stringSize > long :
long = stringSize
if short == 1e9 or long ==-1:
print(-1)
else :
print(short,long)
``` …
=> 2023/08/11 BOJ 20437 [문자열] 문자열 게임2

gibeom/23-08-16.py
#186 
``` python
def bfs(r, c, rain, q: deque):
q.append((r, c))
while q:
for i in range(4): # 상하좌우 순회
if is_out_of_range(nr, nc) or visited[nr][nc] or city[nr][nc] <= rain: # 범위를 벗어났거나 방문했거나 물에 잠긴 지점일 경우 건너뜀
continue
visited[nr][nc] = True # 방문 처리
q.append((nr, nc))
return r < 0 or r >= n or c < 0 or c >= n
max_height = 0 # 지점의 최고 높이
city = []
c = list(map(int, stdin.readline().split()))
max_height = max(max_height, max(c))
city.append(c)
direction = [1, 0, -1, 0]
q = deque()
res = 0
for rain in range(max_height): # 비를 0 ~ 지점의 최고 높이 - 1까지 순회
visited = [[False] * n for _ in range(n)]
area = 0
for r in …
```
=> [BOJ] 2468 : 안전 영역 (23.08.16)

gibeom/23-08-21.py
#188 
``` python
from sys import stdin, setrecursionlimit
def find(x):
if x != parent[x]:
parent[x] = find(parent[x])
return parent[x]
def union(a, b):
a = find(a)
b = find(b)
if a < b:
parent[b] = a
else:
parent[a] = b
setrecursionlimit(10**6)
parent = [i for i in range(n + 1)]
for _ in range(m):
operator, a, b = map(int, stdin.readline().split())
if operator == 0:
union(a, b)
elif operator == 1:
print("YES") if find(a) == find(b) else print("NO")
```
- 76720KB
- 304ms
=> [BOJ] 1717 :  집합의 표현 (23.08.21)

gaeun/2023:08:23BOJ1717.py
#188 
``` python
import sys
n, m = map(int, readline().split())
setList = [i for i in range(n+1)]
def findRoot(ind) :
if setList[ind] != ind :
#자신이 바라보고 있는 루트의 루트를 찾음
setList[ind] = findRoot(setList[ind]) 
return setList[ind]
#실제로 합치는 것이 아닌, 트리구조로 루트,자식으로 관계를 표현
def union(x,y):
#각자가 바라보고 있는 최상위 root
rootX = findRoot(x)
rootY = findRoot(y)
setList[rootY] = rootX
for _ in range(m):
calcul,a,b = map(int,readline().split())
#합집합
if calcul == 0 :
union(a,b)
#조회
else :
if findRoot(a)==findRoot(b):
print("yes")
else :
print("no")
```
처음에는 Set을 직접 구현했는데 메모리 초과가 났다. 사실 어디부분에서 메모리 초과가 발생했는지 찾아보고 싶어서 메모리 누수를 확인하는 코드도 작성해봤지만 딱히 눈에 띄는 곳은 없었다.. 혹시 이유를 아시는 분이 있다면 친절한 설명 부탁드리겠습니당 ,,,ㅜ
- 71248 KB
- 296 ms
=> 2023/08/23 BOJ 1717 집합의 표현 [자료구조]

gibeom/23-08-26.py, gibeom/23-08-27.py, gibeom/23-08-28(1).py, gibeom/23-08-28(2).py, gibeom/23-08-28(3).py, gibeom/23-08-29.py
#191 
``` python
letter = stdin.readline().rstrip()
n = len(letter) # 문자열 길이
palindrome = [[0] * n for _ in range(n)] # 이차원 리스트
dp = [2500] * (n + 1) # 최대 출력값은 2500
dp[-1] = 0
for e in range(n):
for s in range(e + 1):
if letter[s] == letter[e] and (e - s < 2 or palindrome[s + 1][e - 1]): # 시작 문자와 끝 문자가 같고, 현재 길이가 1, 2이거나 내부 문자열이 팰린드롬일 경우
palindrome[s][e] = 1 # 현재 문자열 팰린드롬
dp[e] = min(dp[e], dp[s - 1] + 1) # 현재 길이까지의 팰린드롬 최소 개수 갱신
print(dp[n - 1])
```
- 79548KB
- 2112ms
=> [BOJ] 1509 : 팰린드롬 분할 (23.08.28)

gibeom/23-08-31.py
#193
``` python
def escape():
global ans
maze[jihoon[0][0]][jihoon[0][1]] = -1 # 첫 위치 방문 체크
minutes = 0
while jihoon:
minutes += 1
spread_fire() # 불 확산
for _ in range(len(jihoon)): # 현재 분에 이동할 수 있는 지훈까지
r, c = jihoon.popleft()
for i in range(4): # 4방향 순회
nr, nc = r + direction[i], c + direction[3 - i] # 다음 위치
if is_out_of_range(nr, nc): # 범위를 벗어났을 경우
ans = min(ans, minutes) # 최소 분 갱신
continue
if is_not_space(nr, nc) or maze[nr][nc] == -1: # 벽 또는 불이거나 방문한 위치일 경우
continue
maze[nr][nc] = -1 # 방문 체크
jihoon.append((nr, nc))
def spread_fire():
for _ in range(len(fire)): # 현재 확산할 수 있는 불까지
r, c = fire.popleft()
for i in range(4): # 4방향 순회
nr, nc = r + direction[i], c + direction[3 - i] # 다음 위치
if is_out_of_range(nr, nc) or is_not_space(nr, nc): …
```
=> [BOJ] 4179 : 불! (23.08.31)

yoonjin/0901/4179.py
#193 
``` python
import sys
dr = (-1, 1, 0, 0)
dc = (0, 0, -1, 1)
def fbfs():
while fq:
r, c = fq.popleft()
for d in range(4):
nr = r + dr[d]
nc = c + dc[d]
if not (0 <= nr < R and 0 <= nc < C):
continue
if maze[nr][nc] == "#" or fire[nr][nc]:
continue
fire[nr][nc] = fire[r][c] + 1
fq.append((nr, nc))
def hbfs():
while hq:
r, c = hq.popleft()
for d in range(4):
nr = r + dr[d]
nc = c + dc[d]
if not (0 <= nr < R and 0 <= nc < C):
print(human[r][c])
return
if human[nr][nc] or maze[nr][nc] == "#":
continue
if fire[nr][nc] and human[r][c] + 1 >= fire[nr][nc]:
continue
human[nr][nc] = human[r][c] + 1
hq.append((nr, nc))
print("IMPOSSIBLE")
return
R, C = map(int, input().split())
maze = []
hq = deque()
fq = deque()
human = [[0] * C for _ …
```
=> [23-09-01] BOJ 4179
