co-niverse/algorithm-study

- gibeom/23-04-27.py
https://www.acmicpc.net/problem/4963
`dfs(height, width)`
- 방문한 땅일 경우 0을 할당하여 다시 방문하지 않도록 한다.
- 상하좌우, 대각선 4방향을 순회하면서 범위 안이거나 땅인 경우만 깊이 우선 탐색 실시한다.
<br>
`main`
- 백준의 최대 재귀 깊이는 1,000이므로  `setrecursionlimit()` 메서드로 재귀 깊이를 늘려준다.
- 이중 for문으로 순회하면서 땅일 경우 `dfs()`를 호출하고 cnt를 1 증가시킨다.
> [BOJ] 4963 : 섬의 개수 (23.04.27)

- gibeom/23-05-03.py
https://www.acmicpc.net/problem/12865
꽤나 어려웠던 dp문제,, 두 풀이는 메모리 사용량과 시간이 확연히 차이나는 것을 볼 수 있다.
첫 번째 풀이는 `(n + 1) * (k + 1)` 크기의 2차원 list를 사용하고, 두 번째 for문을 봤을 때 1부터 k까지 순회한다.
두 번째 풀이는 k 이하를 만들 수 있는 무게 조합만 나오고 해당 무게 조합이 dp의 무게보다 작아야만 dp에 저장된다. 그 후 dp를 순회한다. 이 때문에 차이가 나타난다.
효율적인 방법을 항상 고민하기.
> [BOJ] 12865 : 평범한 배낭

- gibeom/23-05-04.py
https://www.acmicpc.net/problem/2512
상한액을 이진 탐색으로 찾는다.
- budget 리스트를 순회하면서 상한액보다 작으면 해당 budget을 더하고, 크면 상한액을 더한다.
- 더한 값이 총 예산(`m`)보다 같거나 작은지 확인한다. 이에 따라 start와 end를 조정한다.
처음에 start를 budget의 최솟값으로 설정했는데 47%에서 실패했다. budget의 최솟값이 m보다 큰 경우도 있기 때문이다. 이 때는 budget 리스트의 모든 요소를 상한액으로 배정해야 한다. 따라서 start를 1로 설정
> [BOJ] 2512 : 예산 (23.05.04)

- gibeom/23-05-05.py
https://www.acmicpc.net/problem/1300
배열 B는 1 ~ N^2까지다. 하지만 N이 최대 10^5이므로 10^10까지 계산하고 배열을 만드는 것은 공간, 시간복잡도에서 초과가 발생할 것이라 생각했다.
그렇다면 k번째 수를 어떻게 찾는지가 관건. 이진 탐색을 하면서 mid 값보다 작거나 같은 수의 개수를 계산한다. 해당 개수를 `k`와 비교한다.
`get_cnt()`
- `mid`보다 작거나 같은 값의 개수를 구하는 메서드
- `i`는 A 배열에서 `i`번째 행을 의미한다.
- `mid`에서 `i`로 나눈 몫을 구하면 `i`번째 행에서 `mid`보다 작거나 같은 수의 개수를 구할 수 있다.
- 배열은 N x N이므로 `mid // i`가 N을 초과하면 안된다. 따라서 두 값 중 최솟값을 리턴한다.
<br>
`binary_search()`
- `k`번째 수는 `k`를 초과하는 값을 가질 수 없다. 따라서 end 값을 `k`로 두어 범위를 줄인다.
- 이진 탐색하여 `mid`를 구하고 `mid` 이하의 개수를 계산한다. -> `get_cnt()`
- `k`와 비교해서 start와 end 범위를 좁힌다.
> [BOJ] 1300 : K번째 수 (23.05.05)

- gibeom/23-05-09.py
https://www.acmicpc.net/problem/14889
조합이 떠올라서 백트래킹이 아닌 조합으로 해결
- 조합 중에서 절반만 돌아야 중복으로 순회하지 않기 때문에 `case_cnt`를 계산해둔다.
- `link_team`은 `start_team`에 속하지 않은 사람이므로 set의 차집합으로 구한다.
- 조합의 경우의 수에 `link_team`도 포함되는데 여기서 미리 로직을 수행하기 때문에 `case_cnt`를 설정한 것
- `get_team_stat()` 메서드로 각 팀의 능력치를 구하고 두 팀의 능력치의 차이를 계산한다.
<br>
다른 사람의 소요 시간과 비교했는데 10배 이상이 차이났다. 하지만 코드가 도저히 이해되지 않았고 나랑 비슷한 사람이 있을까 싶어 게시판을 뒤적였다.
https://www.acmicpc.net/board/view/72643 에서 해설을 찾았다. 풀이법을 이해하고 나니까 기가 막히다고 생각했다. 어떻게 이런 생각을 하지?
- 행렬 `s`가 있을 때 `zip(*s)`를 사용하면 `s`의 전치행렬을 구할 수 있다. 기억해두면 나중에 유용하게 쓸 듯?
> [BOJ] 14889 : 스타트와 링크 (23.05.09)

- gibeom/23-05-17.py
https://www.acmicpc.net/problem/14499
주사위를 어떻게 굴릴지 고민을 많이 했던 문제. 이것만 해결하면 금방 풀리는 문제였다
``` python
def turn(command):
global dice
top, north, east, west, south, bottom = dice
if command == 1: # 동쪽으로 굴리기
dice = [west, north, top, bottom, south, east]
elif command == 2: # 서쪽으로 굴리기
dice = [east, north, bottom, top, south, west]
elif command == 3: # 북쪽으로 굴리기
dice = [south, top, east, west, bottom, north]
else: # 남쪽으로 굴리기
dice = [north, bottom, east, west, top, south]
return r < 0 or r >= n or c < 0 or c >= m
n, m, x, y, k = map(int, stdin.readline().split())
maps = [list(map(int, stdin.readline().split())) for _ in range(n)]
commands = deque(map(int, stdin.readline().split()))
direction = [(0, 1), (0, -1), (-1, 0), …
```
> [BOJ]  14499 : 주사위 굴리기 (23.05.17)

- gibeom/23-05-21.py
https://www.acmicpc.net/problem/14500
``` python
def dfs(depth, total, r, c):
global visited, res
if res >= total + (4 - depth) * max_num: # 현재 depth에서 board의 최댓값(max_num)을 채워도 res에 못 미칠 경우
return
if depth == 4: # 폴리오미노 4개를 모두 탐색했을 경우 리턴
res = max(res, total)
return
for i in range(4): # r, c 좌표의 상하좌우 탐색
nr, nc = r + direction[i], c + direction[3 - i] # 다음 폴리오미노
if is_out_of_range(nr, nc) or visited[nr][nc]: # 범위를 벗어났거나 이미 방문했을 경우
continue
visited[nr][nc] = True # 방문 처리
dfs(depth + 1, total + board[nr][nc], nr, nc)
visited[nr][nc] = False # 같은 폴리오미노를 탐색하는 경우가 있으므로 방문 처리 취소
def tetromino(r, c):
global res
next_polyomino = []
for i in range(4): # r, c 좌표의 상하좌우 탐색
nr, nc = r + direction[i], c + direction[3 - i] # 다음 폴리오미노
if is_out_of_range(nr, nc): # 범위를 벗어났을 경우 …
```
> [BOJ] 14500 : 테트리미노 (23.05.21)

- gibeom/23-05-23.py
https://www.acmicpc.net/problem/16234
``` python
def bfs(r, c):
global flag
visited[r][c] = True
q = deque([(r, c)])
opened = [(r, c)] # 국경을 연 국가의 좌표
tot = country[r][c] # 국경을 연 국가 인구의 합
while q:
for i in range(4): # 상하좌우 탐색
if is_out_of_range(nr, nc) or visited[nr][nc]: # 땅을 벗어났거나 이미 방문했을 경우 건너뛰기
continue
if is_within_population(r, c, nr, nc): # 인구 수 차이가 L과 R 사이인 경우
visited[nr][nc] = True # 방문 처리
tot += country[nr][nc] # 인구 수 추가
q.append((nr, nc)) # 다음 bfs 추가
opened.append((nr, nc)) # 국경을 연 국가에 추가
if len(opened) > 1: # 국경을 연 국가가 있을 경우
flag = 1 # 인구 이동 flag
move(opened, tot) # 인구 이동
return r < 0 or r >= N or c < 0 or c >= N
def …
```
> [BOJ] 16234 : 인구 이동 (23.05.23)

- gibeom/23-05-27.py
https://www.acmicpc.net/problem/14891
``` python
def dfs(now, d):
global visited
if visited[now] == cnt: # 현재 회전 횟수에 이미 방문했으면 리턴
return
visited[now] = cnt
left = gears[now][6] # 현재 톱니바퀴의 왼쪽 극
right = gears[now][2] # 현재 톱니바퀴의 오른쪽 극
if now - 1 >= 0 and left != gears[now - 1][2]: # 다음 톱니바퀴의 오른쪽 극과 다르면 dfs
dfs(now - 1, d * -1)
if now + 1 < 4 and right != gears[now + 1][6]: # 다음 톱니바퀴의 왼쪽 극과 다르면 dfs
dfs(now + 1, d * -1)
if d == 1:
gears[now].appendleft(gears[now].pop()) # 시계 방향 회전
else:
gears[now].append(gears[now].popleft()) # 반시계 방향 회전
gears = [deque(stdin.readline().rstrip()) for _ in range(4)]
k = int(stdin.readline())
visited = [-1] * 4
cnt = 0 # 회전 횟수
while cnt < k:
now, d = map(int, stdin.readline().split()) # 회전시킨 톱니바퀴 번호, 방향
dfs(now - …
```
> [BOJ] 14891 : 톱니바퀴 (23.05.27)

- gibeom/23-05-29.py
https://www.acmicpc.net/problem/15683
``` python
def dfs(office, idx):
global res
if idx >= len(cctv): # 모든 cctv를 탐색했을 경우
blind_spot = sum(o.count(0) for o in office) # 사각 지대 크기 (0의 개수)
res = min(res, blind_spot) # 최솟값 갱신
return
r, c = cctv[idx]
if office[r][c] == 1: # 1번 cctv
for i in range(4): # 90도로 회전하면 경우의 수 4개
tmp_office = [o[:] for o in office] # deep copy
watch(tmp_office, r, c, direction[i][0], direction[i][1]) # 감시 영역 표시
dfs(tmp_office, idx + 1) # 다음 cctv dfs 탐색
elif office[r][c] == 2: # 2번 cctv
for i in range(2): # 90도로 회전하면 경우의 수 2개
tmp_office = [o[:] for o in office]
watch(tmp_office, r, c, direction[i][0], direction[i][1])
watch(tmp_office, r, c, -direction[i][0], -direction[i][1])
dfs(tmp_office, idx + 1)
elif office[r][c] == 3: # 3번 cctv
for i in …
```
> [BOJ] 15683 : 감시 (23.05.29)

- gibeom/23-06-15.py
https://www.acmicpc.net/problem/20055
``` python
def rotate_belt():
belt.appendleft(belt.pop())
robot.appendleft(robot.pop())
if robot[-1]: # n - 1 index에 로봇이 있으면 로봇 내림
robot[-1] = False
def move_robot():
for i in range(n - 2, -1, -1):
if robot[i] and not robot[i + 1] and belt[i + 1] > 0: # 현재 index에 로봇이 있고, 다음 index에 로봇이 없고, 내구도가 1 이상일 경우
if i + 1 == n - 1: # 다음 index가 n - 1이면 로봇 내림
robot[i] = False
else: # 이외의 index는 한 칸 이동
robot[i], robot[i + 1] = False, True
decrease_durability(i + 1) # 다음 index 내구도 감소
def put_robot():
if not robot[0] and belt[0] > 0: # 0번 index에 로봇이 없고 내구도가 1 이상일 경우
robot[0] = True # 로봇 놓음
decrease_durability(0) # 0번 index 내구도 감소
def decrease_durability(idx):
global durability_zero
belt[idx] -= 1 # 내구도를 1 감소시킴
if …
```
> [BOJ] 20055 : 컨베이어 벨트 위의 로봇 (23.06.15)

- yoonjin/0619/11724.py
[11724](https://www.acmicpc.net/problem/11724)
``` python
import sys
sys.setrecursionlimit(5000)
def dfs(v):
visited[v] = True
for e in graph[v]:
if not visited[e]:
dfs(e)
n,m = map(int, input().split())
graph = [[] for _ in range(n+1)]
visited = [False] * (n+1)
count = 0
for i in range(m):
u, v = map(int, input().split())
graph[u].append(v)
graph[v].append(u)
for j in range(1, n+1):
if not visited[j]:
dfs(j)
count += 1
print(count)
```
- 65148KB
- 680ms
- setrecursionlimit 함수를 사용했는데도 계속 시간 초과가 떴다.
- input = sys.stdin.readline 을 작성하니까 통과가 되었는데, input 정의해주는걸 어떤 상황에서 해야되는지는 잘모르겠다 ..
dfs 문제에서 인접리스트를 사용해서 풀고, 양방향으로 append를 대칭으로 해줘야하는 것을 알게되었다.
> [23-06-19] BOJ 11724

- gibeom/23-06-23.py
#76 
``` python
def dfs(r, c, now_cnt):
global max_cnt
if alphabet[board[r][c]]: # 지나온 알파벳일 경우 최대 칸 수를 갱신하고 리턴
max_cnt = max(max_cnt, now_cnt)
return
alphabet[board[r][c]] = True # 방문 체크
for i in range(4): # 상하좌우 순회
nr, nc = r + direction[i], c + direction[3 - i] # 다음 칸
if 0 <= nr < R and 0 <= nc < C: # 범위 내일 경우 dfs 탐색
dfs(nr, nc, now_cnt + 1)
alphabet[board[r][c]] = False # 방문 체크 해제
R, C = map(int, stdin.readline().split())
board = [list(map(lambda x: ord(x) - 65, stdin.readline().rstrip())) for _ in range(R)] # 알파벳을 0 ~ 25의 숫자로 변경하여 저장
alphabet = [False] * 26 # 지나온 알파벳 확인용 리스트
direction = [1, 0, -1, 0]
max_cnt = 0
dfs(0, 0, 0)
print(max_cnt)
```
PyPy3
- 166452KB
- 5720ms
시간 초과가 계속 나서 애를 먹었다. 찾아보니까 dfs로 풀었을 경우 `PyPy3`로 제출해야 하고, bfs로 풀었을 경우 `Python3`로 제출해도 된다고 한다
> [BOJ] 1987 : 알파벳 (23.06.23)

- gibeom/23-06-26.py
#79
``` python
def decrease(idx):
global durability
robot[idx] = True
belt[idx] -= 1 # 내구도 감소
if belt[idx] == 0: # 내구도가 0이면 durability 1 증가
durability += 1
n, k = map(int, stdin.readline().split())
belt = deque(map(int, stdin.readline().split()))
robot = deque([False] * n)
step, durability = 0, 0
while durability < k:
belt.rotate() # 벨트 회전
robot.rotate() # 로봇 회전
robot[0] = False # 회전하기전 마지막 index가 True인 경우때문에 False 처리
robot[-1] = False # 로봇 이동 -> 마지막 index는 내리는 위치이므로 False 처리
for i in range(n - 2, -1, -1):
if not robot[i + 1] and robot[i] and belt[i + 1] > 0: # 앞 index에 로봇이 없으면서 내구도가 있고, 현재 index에 로봇이 있으면
robot[i] = False
decrease(i + 1)
if belt[0] > 0: # 올리는 위치에 내구도가 있으면
decrease(0)
step += 1
print(step)
```
- 34140KB
- 2908ms
11일 전에 …
> [BOJ] 20055 : 컨베이어 벨트 위의 로봇 (23.06.26)

- gibeom/23-06-27.py
#83
``` python
def dfs(res, idx):
global max_res, min_res
if idx == n: # 숫자를 모두 탐색했을 경우 최댓값, 최솟값을 갱신하고 리턴
max_res = max(max_res, res)
min_res = min(min_res, res)
return
if operators[i] > 0: # 연산자가 있을 때
operators[i] -= 1
if i == 0: # + 연산자
dfs(res + nums[idx], idx + 1)
elif i == 1: # - 연산자
dfs(res - nums[idx], idx + 1)
elif i == 2: # * 연산자
dfs(res * nums[idx], idx + 1)
else: # / 연산자
dfs(int(res / nums[idx]), idx + 1) # res가 음수일 수 있기 떄문에 // 는 사용불가
operators[i] += 1
nums = list(map(int, stdin.readline().split()))
operators = list(map(int, stdin.readline().split()))
max_res = int(-1e9) # 결과는 -10억보다 크거나 같음
min_res = int(1e9) # 결과는 10억보다 작거나 같음
dfs(nums[0], 1)
print(max_res)
print(min_res)
```
- 31256KB
- 76ms
`max_res`, …
> [BOJ] 14888 : 연산자 끼워넣기 (23.06.27)

- gibeom/23-06-28.py
#87 
``` python
from sys import stdin, setrecursionlimit
def dfs(now):
for next, weight in tree[now]:
if distance[next] != -1: # 방문한 노드는 건너뜀
continue
distance[next] = distance[now] + weight # 길이 갱신
dfs(next)
setrecursionlimit(10**6)
tree = [[] for _ in range(n)]
for _ in range(n - 1):
a, b, w = map(int, stdin.readline().split())
tree[a - 1].append((b - 1, w))
tree[b - 1].append((a - 1, w))
distance = [-1] * n
distance[0] = 0
dfs(0) # 루트 노드에서 각 노드까지의 길이 탐색
max_node = distance.index(max(distance)) # 루트 노드에서 가장 먼 노드
distance = [-1] * n
distance[max_node] = 0
dfs(max_node) # 가장 먼 노드에서 각 노드까지의 길이 탐색
print(max(distance))
```
어느 한 노드에서 가장 먼 노드 `A`를 찾고 `A`노드에서 가장 먼 노드 `B`를 찾으면, `A`에서 `B`까지의 거리가 트리의 지름이 된다.
- 35572KB
- 76ms
이전에 풀었었던 https://www.acmicpc.net/problem/1167 …
> [BOJ] 1967 : 트리의 지름 (23.06.28)

- gibeom/23-07-07.py
#107
``` python
def dfs(i, record):
global max_record
if i == 10: # 주사위를 모두 굴렸을 때
max_record = max(max_record, record) # 점수 최댓값 갱신
return
elif record + 40 * (10 - i) < max_record: # 백트래킹
return # 남은 주사위 횟수를 모두 굴렸을 때 전부 40점이어도 최댓값보다 작을 경우 주사위를 더 이상 굴리지 않는다
now_dice = dices[i] # 현재 주사위에서 나온 수
for k in range(4): # 말 순회
if arrived[k]: # 이미 도착한 말일 경우
continue
tmp = [players[k][0], players[k][1]]
r, c = players[k][0], players[k][1] + now_dice # 주사위 수만큼 전진
if len(board[r]) - 1 < c: # 말이 게임판을 나갔을 경우 (도착점 이상의 r, c)
players[k][0], players[k][1] = r, c
arrived[k] = True # 도착한 말 체크
dfs(i + 1, record) #  도착한 말은 점수 없음
arrived[k] = False
players[k][0], players[k][1] = tmp
continue
if board[r][c] == 40: # 말이 위치한 칸의 숫자가 40일 경우
r, c = 4, 0
elif r == 0 and board[r][c] % 10 == 0: # 0번 …
```
> [BOJ] 17825 : 주사위 윷놀이 (23.07.07)

- yoonjin/0710/1946.py
#113 
``` python
import sys
T = int(input())
for i in range(T):
num = int(input())
score = []
answer = 0
for j in range(num):
write, speak = map(int, input().split())
score.append((write, speak))
for write_t, speak_t in score:
count = 0
for l in range(num):
if (write_t > score[l][0]) and (speak_t > score[l][1]):
break
else:
count += 1
if count == num:
answer += 1
print(answer)
import sys
T = int(input())
for i in range(T):
num = int(input())
write_score = []
speak_score = []
answer = 0
for j in range(num):
write, speak = map(int, input().split())
write_score.append(write)
speak_score.append(speak)
for k in range(num):
write_t = write_score[k]
speak_t = speak_score[k]
if (write_t == max(write_score)) and (speak_t == max(speak_score)): …
```
> [23-07-10] BOJ (1946)

- gibeom/23-07-12.py
#122 
``` python
crane = sorted(list(map(int, stdin.readline().split())), reverse=True) # 역순으로 정렬
_ = int(stdin.readline())
box = deque(sorted(map(int, stdin.readline().split()), reverse=True)) # 역순으로 정렬
if box[0] > crane[0]: # 크레인의 무게 제한보다 큰 박스가 있을 경우
print(-1)
exit()
batch_crane = [0] * n # 각 크레인마다 박스를 옮긴 개수
while box:
b = box.popleft()
worker, min_batch = 0, batch_crane[0]
for i in range(1, n):
if crane[i] >= b: # 박스를 옮길 수 있을 때
if batch_crane[i] < min_batch: # 해당 크레인이 옮긴 개수가 가장 작으면
worker = i # 박스를 옮길 대상이 됨
min_batch = batch_crane[i]
else:
break # 박스를 옮길 수 없으면 탈출 -> 역순으로 정렬했기 때문에 가능
batch_crane[worker] += 1
print(max(batch_crane))
```
- 34160KB
- 68ms
> [BOJ] 1092 : 배 (23.07.12)

- gibeom/23-07-15.py
#132
``` python
def fly():
honey_amount = 0
for i in range(1, n - 1):
bee_1 = accum_honey[n - 1] - honey[i] - honey[0] # 꿀 총합에서 벌1, 벌2 시작 위치 빼기
bee_2 = accum_honey[n - 1] - accum_honey[i] # 꿀 총합에서 벌2 시작 위치까지의 누적합 빼기
honey_amount = max(honey_amount, bee_1 + bee_2)
bee_1 = accum_honey[i] - honey[0] # 벌통까지의 누적합에서 벌1 시작 위치 빼기
bee_2 = accum_honey[n - 2] - accum_honey[i - 1] # 2번 벌은 n - 1에 있기 떄문에 n - 2까지의 누적합에서 벌통 전까지의 누적합 빼기
honey_amount = max(honey_amount, bee_1 + bee_2)
bee_1 = accum_honey[i - 1] # 벌1 시작 위치 전까지의 누적합
bee_2 = accum_honey[n - 2] - honey[i] # n - 2까지의 누적합에서 벌1 시작 위치 뺴기
honey_amount = max(honey_amount, bee_1 + bee_2)
return honey_amount
honey = list(map(int, stdin.readline().split()))
accum_honey = honey[:] 
for i in range(1, n): # …
```
> [BOJ] 21758 : 꿀 따기

- gibeom/23-07-27.py
#162
``` python
n, t = map(int, stdin.readline().split()) # 단원 개수, 총 공부시간
dp = [0] * (t + 1)
k, s = map(int, stdin.readline().split()) # 예상 공부시간, 배점
for i in range(t, k - 1, -1): # t부터 k까지 역순으로 순회
dp[i] = max(dp[i], dp[i - k] + s) # 현재 index의 배점과 i - k번째 index 배점에 s을 더한 값 중 최댓값
print(dp[t])
```
역순으로 순회하기 떄문에 `i - k`index는 아직 k가 반영되지 않은 배점이다. 따라서 s를 더해도 중복 계산이 되지 않는다
- 31256KB
- 368ms
> [BOJ] 14728 : 벼락치기 (23.07.27)

- gibeom/23-08-01.py
#170
``` python
letter_1 = stdin.readline().rstrip()
letter_2 = stdin.readline().rstrip()
dp = [[0] * (len(letter_2) + 1) for _ in range(len(letter_1) + 1)] # 2차원 리스트
for i in range(1, len(letter_1) + 1):
for j in range(1, len(letter_2) + 1):
if letter_1[i - 1] == letter_2[j - 1]: # 두 문자가 같으면
dp[i][j] = dp[i - 1][j - 1] + 1 # 1번, 2번 문자가 추가되기 전의 dp 값 + 1
else: # 두 문자가 다르면
dp[i][j] = max(dp[i][j - 1], dp[i - 1][j]) # 1번 문자가 추가되기 전의 dp 값과 2번 문자가 추가되기 전의 dp 값 중 최댓값
print(dp[-1][-1])
```
https://velog.io/@emplam27/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-%EA%B7%B8%EB%A6%BC%EC%9C%BC%EB%A1%9C-%EC%95%8C%EC%95%84%EB%B3%B4%EB%8A%94-LCS-%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-Longest-Common-Substring%EC%99%80-Longest-Common-Subsequence
쉽게 설명되어 있으니 참고 바람!
<br>
``` python
from sys …
```
> [BOJ] 9251 : LCS (23.08.01)

- gibeom/23-08-10.py
#181 
``` python
def find_top(board, c):
for r in range(2, 6): # 0, 1 행은 항상 블록이 없으므로 제외
if board[r][c] == 1:
return r - 1
return 5
def remove_full_col():
global res
for board in blue, green:
for r in range(2, 6): # 0, 1 행은 항상 블록이 없으므로 제외
if sum(board[r]) == 4: # 열이 꽉 찼을 때
del board[r] # 해당 행 삭제
board.appendleft([0] * 4) # 맨 앞에 행 추가
res += 1 # 점수 +1
def execute_special():
for board in blue, green:
while 1 in board[1]:
board.pop()
board.appendleft([0] * 4)
blue = deque([deque([0] * 4) for _ in range(6)]) # blue는 90도 돌려서 green과 같은 모양으로 시작
green = deque([deque([0] * 4) for _ in range(6)])
res = 0
t, r, c = map(int, stdin.readline().split())
br, gr = find_top(blue, r), find_top(green, c) # 블록을 놓을 수 …
```
> [BOJ] 20061 : 모노미노도미노 2 (23.08.10)

- gibeom/23-09-01.py
#197
``` python
c, n = map(int, stdin.readline().split())
city = [list(map(int, stdin.readline().split())) for _ in range(n)]
dp = [1e9] * (c + 1) # index는 고객 수, value는 해당 고객 수를 얻을 수 있는 최소 비용
dp[0] = 0
for i in range(1, c + 1):
for cost, customer in city:
if i <= customer: # i 고객 수 이상을 모두 만들 수 있으면
dp[i] = min(dp[i], cost) # 현재 도시의 비용과 최솟값 갱신
else: # 만들 수 없으면
dp[i] = min(dp[i], dp[i - customer] + cost) # i - customer의 비용 + 현재 도시의 비용과 최솟값 갱신
print(dp[-1])
```
- 31256KB
- 52ms
> [BOJ] 1106 : 호텔 (23.09.01)
